livingdocsIO/documentation

- data-migrations/migrations.md
@gabrielhase undesirability for this document was ok for me, just a typo.
> doc: fix dead link

- README.md
- core/guides/design/local-design.md
- core/guides/local-development/docker.md
- core/guides/local-development/editor-and-service-server.md
- core/guides/local-development/editor-only.md
- core/guides/local-development/link-local-dependencies.md
- core/guides/local-development/local-design.md
- core/guides/local-development/node.md
Related to: https://github.com/upfrontIO/livingdocs-planning/issues/15
> First guides

- contribution-guidelines/npm/access.md
- contribution-guidelines/npm/publishing.md
@marcbachmann This is a PR of you from the upfrontIO/guides which is now merged in upfrontIO/livingdocs
> docs(npm): Update release docs

- core/livingdocs-editor/configurable-metadata-screen.md
https://github.com/upfrontIO/livingdocs-editor/pull/1226
> Update metadata description with text service

- contribution-guidelines/readme.md
- contribution-guidelines/style-guides/blacklisted-packages.md
@marcbachmann is this enough for https://github.com/upfrontIO/livingdocs-planning/issues/64
> feat: adds blacklisted packages to the guidelines

- README.md
- public/design/create_designs.md
@peyerluk: Gabriel ask me to add a missing link (design document) in the main README.
> fix(public): add missing link to create_designs

- README.md
- core/livingdocs-server/document_copy_feature.md
Documentation for the document-copy feature.
> feat(document-copy): add documentation for document-copy feature

- README.md
- public/APIs/events.md
@peyerluk first draft for the events API documentation.
> docs(events): in the public API

- README.md
- core/livingdocs-editor/styleguide.md
@rawdiggie: do you remember that we said we wanted to do a techtalk about that :smile: ?
In the meantime let's make a documentation page about it, feel free to contribute !
> docs(styleguide): custom directives

- contribution-guidelines/collaboration/bug-reports.md
Licecap's repo seems to be nonexistent and the new repo's last commit is from August 2015, company's link seems to be the most appropriate
> Update not existing link

- concepts/metadata/metadata-examples.md
- reference-docs/editor-configuration/metadata.md
- reference-docs/server-configuration/metadata.md
While working on a metadata plugin i realised some links where broken and i fixed them.
> Fixed some links for metadata related docu

- reference-docs/server-public-api/routing-system.md
Continuation of https://github.com/upfrontIO/livingdocs/pull/75
@masone I took your review into account.
@peyerluk Please check that this file is at the right location, a bunch of things moved around since that PR was first opened.
> docs(api): Routing system

- reference-docs/common-designs/design_config.md
Add the design config `layouts` option to the readme.
> Design: add layouts config option

- reference-docs/server-configuration/config.md
Describe the current state of the docker config option.
> Describe server config 'docker' option

- reference-docs/common-designs/component_config.md
Documentation for this PR: https://github.com/upfrontIO/livingdocs-editor/pull/1590
> fix(component-config): Add textcounter config docu

- concepts/copying-documents/document_copy_feature.md
Docs for https://github.com/upfrontIO/livingdocs-server/pull/1464
> docs: Add documentation for custom transformations

- concepts/document-migrations/migrations.md
Related to the Automatic Migration Feature: https://github.com/upfrontIO/livingdocs-server/pull/1367
> doc: Automatic selection of migrations

- concepts/document-migrations/migrations.md
Reverts upfrontIO/livingdocs#84
> Revert "doc: Automatic selection of migrations"

- reference-docs/README.md
- reference-docs/maintenance/how-to-do-a-load-test.md
https://github.com/upfrontIO/livingdocs-planning/issues/1209
> Add Load Test Documentation

- reference-docs/common-designs/component_config.md
- reference-docs/common-livingdoc/component_model.md
Some things I noticed while reading the docs.
> Small fixes and updates for framework docs

- SUMMARY.md
- reference-docs/server-configuration/config.md
- reference-docs/server-configuration/stack.md
@gabrielhase Can you review?
Also, I can't find the file to change the gitbook summary.
> docs: add server stack definition and config

- reference-docs/server-extensions/server-initalization.md
Documentation updates for the august release.
> August Release (maintenance-2017-08)

- SUMMARY.md
- reference-docs/maintenance/how-to-varnish.md
https://github.com/upfrontIO/livingdocs-planning/issues/1208
> Analyze Varnish Numbers

- concepts/copying-documents/document_copy_feature.md
- reference-docs/maintenance/how-to-do-a-load-test.md
- reference-docs/maintenance/release-management/index.md
- reference-docs/server-configuration/config.md
- reference-docs/server-configuration/metadata.md
Pull Request: https://github.com/upfrontIO/livingdocs-server/pull/1617
> Update Documentation Regarding the `grunt setup` fix for Docker Containers

- reference-docs/server-configuration/channel-config.md
Related to planning issue 1348
> docs(hooks): Document documents and render hooks

- reference-docs/editor-configuration/search-filters.md
Some enhancements to your PR @gabrielhase 
Please also check rich diff here: https://github.com/upfrontIO/livingdocs/pull/140/files?short_path=ec3d3a0#diff-ec3d3a05f67da2a478907f7049a04729
Please merge yourself if you agree with the changes. 😃
> chore: Fix code examples and add comments

- DICTIONARY.md
- GLOSSARY.md
- SUMMARY.md
* Add up/downstream term to the glossary
* Introduce alphabetical order
> Add up/downstream term to the glossary

- SUMMARY.md
Introduce a reference section and clearly mark design and customizing as guides.
> Reference and Guides

- concepts/images/image-services.md
https://github.com/upfrontIO/livingdocs-planning/issues/1532
@gabrielhase can you review?
> doc: image services configuration

- SUMMARY.md
- reference-docs/server-import-api/import_api.md
Issue: https://github.com/upfrontIO/livingdocs-planning/issues/1624
> Add documentation on Import API

- reference-docs/common-designs/component_config.md
- reference-docs/common-livingdoc/component_model.md
- reference-docs/common-livingdoc/directives.md
depends on pr: [Server side one-time rendering](https://github.com/upfrontIO/livingdocs-framework/pull/161)
> Include directive setParams()

- concepts/copying-documents/document_copy_feature.md
- reference-docs/common-designs/design_config.md
- reference-docs/editor-configuration/metadata.md
- reference-docs/editor-configuration/search-filters.md
- reference-docs/server-configuration/channel-config.md
- reference-docs/server-configuration/config.md
- reference-docs/server-configuration/content-type-config.md
- reference-docs/server-configuration/hooks.md
- reference-docs/server-configuration/metadata.md
- walkthroughs/metadata/metadata-examples.md
ReleaseNotes PR that goes with this: https://github.com/upfrontIO/livingdocs-release-notes/pull/9
> Add contentType documentation

- concepts/copying-documents/document_copy_feature.md
- reference-docs/common-designs/design_config.md
- reference-docs/editor-configuration/metadata.md
- reference-docs/editor-configuration/search-filters.md
- reference-docs/server-configuration/channel-config.md
- reference-docs/server-configuration/config.md
- reference-docs/server-configuration/content-type-config.md
- reference-docs/server-configuration/hooks.md
- reference-docs/server-configuration/metadata.md
- walkthroughs/metadata/metadata-examples.md
- Updated docs for ContentTypes
- Added Design-Loader configuration options
- Added Elasticsearch version config
> Documentation for release-2018-01

- SUMMARY.md
- reference-docs/editor-configuration/editing-features.md
https://github.com/upfrontIO/livingdocs-planning/issues/1652
> Document History Options

- reference-docs/server-configuration/logging.md
Add description of how to create a child logger.
> Add child logger description

- reference-docs/editor-configuration/editing-features.md
Reverting: https://github.com/upfrontIO/livingdocs/pull/165#issuecomment-367325437
> docs: revert transform component config

- reference-docs/common-designs/component_config.md
https://github.com/upfrontIO/livingdocs-framework/pull/330
> Add tagWhitelist and tagBlacklist doc-editable configs

- concepts/document-migrations/migrations.md
Documentation for the skip migration feature implemented in https://github.com/upfrontIO/livingdocs-server/pull/1951
> Documentation for skip migration feature

- concepts/document-migrations/migrations.md
Implementation: https://github.com/upfrontIO/livingdocs-server/pull/1956
> Documentation for systemdata in migration files

- SUMMARY.md
- reference-docs/server-configuration/single_sign-on.md
> docs: new SSO

- concepts/copying-documents/document_copy_feature.md
@DaRaFF  please check. 
Documentation for https://github.com/upfrontIO/livingdocs-server/pull/1962
> fix(copy):extend documentation for copy from systemdata

- reference-docs/common-designs/component_config.md
- reference-docs/common-designs/design_config.md
- reference-docs/common-livingdoc/component_model.md
- reference-docs/editor-configuration/metadata.md
- reference-docs/server-configuration/content-type-config.md
Pull Requests:
- https://github.com/livingdocsIO/livingdocs-editor/pull/2037
- https://github.com/livingdocsIO/livingdocs-server/pull/1965
> add documentation for component icons

- concepts/copying-documents/document_copy_feature.md
- reference-docs/editor-configuration/editing-features.md
- reference-docs/server-configuration/channel-config.md
Issues:
- livingdocsIO/livingdocs-planning#1959
- https://github.com/livingdocsIO/livingdocs-planning/issues/2078
Relations:
- NZZ Transform PR's
- https://github.com/livingdocsIO/livingdocs-server/pull/2092
- https://github.com/livingdocsIO/livingdocs-editor/pull/2251
- Swisscom Copy PR's
- https://github.com/livingdocsIO/livingdocs-editor/pull/2263
- https://github.com/livingdocsIO/livingdocs-server/pull/2099
> Update description of document-copy feature

- reference-docs/editor-configuration/editing-features.md
https://github.com/livingdocsIO/livingdocs-editor/pull/2381
> Document how to enable undo redo buttons

- SUMMARY.md
- walkthroughs/enable-soft-lock.md
Issue: https://github.com/livingdocsIO/livingdocs-planning/issues/2354
PRs:
- https://github.com/livingdocsIO/livingdocs-server/pull/2230
- https://github.com/livingdocsIO/livingdocs-editor/pull/2455
> Enable soft lock

- concepts/copying-documents/document_copy_feature.md
- Change source to sourceMetadata (source was not implemented yet)
Depends on PR https://github.com/livingdocsIO/livingdocs-server/pull/2233/
> fix(document-copy): fix copy-instructions

- reference-docs/editor-configuration/editing-features.md
- Added advanced component groups to features section
> chore(features): Update

- SUMMARY.md
- reference-docs/editor-configuration/image-source-policy.md
The PR https://github.com/livingdocsIO/livingdocs/pull/208 was merged to late into the release-branch...
> Add image source policy docs

- reference-docs/editor-configuration/editing-features.md
Merge once the November release has hit the boilerplates.
> External link in main menu

- walkthroughs/getting-started-with-local-development.md
Actually link README's as mentioned in livingdocsIO/livingdocs-planning#2549
> Actually link README's #2549

- SUMMARY.md
- reference-docs/editor-configuration/document-drag-drop.md
Add Documentation for custom Drag & Drop Handlers
> feat(dragdrop): add custom drag and drop handler docs

- walkthroughs/getting-started-with-local-development.md
Related to livingdocsIO/livingdocs-planning#2549.
I'd really like to give a little "further reading" to each of the two introductory paragraphs on each boilerplate. Any suggestions? Just point to the reference?
> Getting started locally overhaul

- README.md
- SUMMARY.md
- getting_started.md
- walkthroughs/evaluation_guide.md
- walkthroughs/getting_started.md
We would like to have an entry point for people they start with the evaluation from livingdocs. It should be a help to start with the setup and know which step they have to do and read through the documentation.
> Add Evaluation guide

- reference-docs/server-configuration/config.md
Add the convert option to the config documentation.
> fix(add-convert-option): add the convert option to the config

- reference-docs/server-configuration/config-storage-options.md
- reference-docs/server-configuration/config.md
Add docs for the `storage` config option that is used in various features in the server config.
> Add docs for configuring feature storage

- reference-docs/editor-configuration/menu-and-dashboards.md
We are adding a new filter-type and they should be described in the documentation.
> fix(dashboards): add filter by channelHandle

- reference-docs/server-configuration/config.md
Related PR: https://github.com/livingdocsIO/livingdocs-server/pull/2297
> Minor wording improvements on creation of the the ES Image Index

- reference-docs/editor-configuration/editing-features.md
Add the new config for the changes view to the documentation.
> add changes view config documentation

- SUMMARY.md
- reference-docs/server-seed-api/seed_api.md
This PR adds documentation for the seed api.
> docs(seed): add documentation for initial seed api

- reference-docs/editor-configuration/editing-features.md
Update the diff config name to the new config name `diffViewEnabled`
> updated the diff view enable config name

- reference-docs/editor-configuration/metadata.md
- reference-docs/server-configuration/content-type-config.md
- reference-docs/server-configuration/metadata.md
- walkthroughs/metadata/metadata-examples.md
- walkthroughs/setup_multilanguage.md
Update metadata examples to use the new config format (channelConfig v2)
> Use new config format for metadata examples

- SUMMARY.md
- walkthroughs/add-custom-realtime-proofreading-dashboard.md
The goal of this walkthrough is to show how to set up a "Custom Realtime Proofreading Task Dashboard".
> Add Custom Realtime Proofreading Task Dashboard

- reference-docs/editor-configuration/menu-and-dashboards.md
- Issue: https://github.com/livingdocsIO/livingdocs-planning/issues/2886
- PR: https://github.com/livingdocsIO/livingdocs-editor/pull/2871
> add new configurable menu list filters to documentation

- reference-docs/server-configuration/config.md
Add the pagination config for the document-lists to the server configuration documentation.
> add pagination config for document-lists

- reference-docs/editor-configuration/menu-and-dashboards.md
Update angular component filter example (from directives to components)
> Update angular component filter example (from directives to components)

- reference-docs/editor-configuration/menu-and-dashboards.md
- Fixxes small typo in a config leading to the editor crashing
> Chore: update typo

- SUMMARY.md
- reference-docs/server-configuration/publication-index.md
> Add documentation for "Search publications"

- reference-docs/editor-configuration/text-editing.md
Update how to exclude directives from the text-counter.
> fix(text-editing): update text counter docs

- reference-docs/editor-configuration/menu-and-dashboards.md
Update dashboard kanban board example to use the current config options.
> fix(dashboards): update config options

- reference-docs/common-designs/component_config.md
- reference-docs/common-designs/create_designs.md
- reference-docs/common-designs/list_example.md
- reference-docs/doc-includes/embed_and_list.md
- service/design_example.md
- walkthroughs/twitter_include_embed.md
- Update examples to use design version 2 and directive configs as arrays.
> Design examples update

- reference-docs/server-configuration/config.md
> New Login Device Detection

- reference-docs/server-configuration/channel-config.md
- reference-docs/server-configuration/config.md
Relations:
- Issue: https://github.com/livingdocsIO/livingdocs-planning/issues/3359
- Related PR:
- https://github.com/livingdocsIO/livingdocs-server/pull/2849
- https://github.com/livingdocsIO/livingdocs-editor/pull/3333
> feat(integrations): add documentation for the new integrations feature

- reference-docs/editor-configuration/image-source-policy.md
- reference-docs/server-configuration/channel-config.md
- reference-docs/server-configuration/content-type-config.md
- Update outdated docs for the `imageSourcePolicy` configuration.
> fix(config): update imageSourcePolicy docs

- reference-docs/server-configuration/config.md
Server PR: https://github.com/livingdocsIO/livingdocs-server/pull/2873
Editor PR: https://github.com/livingdocsIO/livingdocs-editor/pull/3358
Issue: https://github.com/livingdocsIO/livingdocs-planning/issues/3467
> feat: add configs for enforcing image metadata

- reference-docs/server-configuration/channel-config.md
This changes the channelConfig example to v2.
> fix(channel config): migrate channelConfig doc to v2

- reference-docs/server-configuration/config.md
For the change, see here: https://github.com/livingdocsIO/livingdocs-server/pull/2969
> Adapt Google Vision description

- SUMMARY.md
- reference-docs/common-designs/component_config.md
- reference-docs/common-designs/create_designs.md
- reference-docs/common-designs/design_config_v1_to_v2.md
- reference-docs/common-designs/design_config_v2.md
- Link to new v2 design description form main navigation
- Fix v2 `componentProperties`
> fix(design): move all designs docs to v2

- reference-docs/editor-configuration/menu-and-dashboards.md
Add dashboard filter example with more complex metadata structures.
> Filter: add dashboard filter example with more complex metadata structures.

- reference-docs/server-api/data_source_api.md
PR: https://github.com/livingdocsIO/livingdocs-editor/pull/3896
> Add explanation for the params attribute

- guides/prefill-author.md
- reference-docs/editor-configuration/metadata.md
https://github.com/livingdocsIO/livingdocs-editor/pull/3780
> fix: add displayfilter configs to the documentation liMetaReferenceForm

- guides/register_custom_dashboard_filters.md
- reference-docs/editor-api/vue-component-registry.md
Add documentation on how to register filters in vue via the `vueComponentRegistry`
Editor PR: https://github.com/livingdocsIO/livingdocs-editor/pull/3777
> feat: add vue filter documentation

- reference-docs/includes/editor_customization.md
This adapts the Include Editor Customizations page to include an example of a Vue component and mention that the AngularJS option will be phased out.
> (doc): add the vue component option to include editor customization

- reference-docs/project-config/directives/video.md
- reference-docs/project-config/media_types.md
We have added the `mediaVideo` MediaType and the video directive.
> add video mediaType and video directive

- guides/push_notifications.md
- reference-docs/server-configuration/config.md
Add the documentation for the urban airship implementation
> add airship documentation

- reference-docs/includes/article_and_list_includes.md
This improves the list include example with code how to get documents from a list id.
> doc(list include): improve list include example

- SUMMARY.md
- reference-docs/server-configuration/config.md
- reference-docs/server-configuration/custom-index.md
- reference-docs/server-configuration/publication-index.md
Issue: https://github.com/livingdocsIO/livingdocs-planning/issues/3610
PR: https://github.com/livingdocsIO/livingdocs-server/pull/3185
> Doc for Custom Elasticsearch Index

- reference-docs/server-configuration/config.md
Add documentation for video storage config
> add video storage config

- reference-docs/project-config/editor_settings.md
Issue: https://github.com/livingdocsIO/livingdocs-planning/issues/3859
> doc(editorSettings): enhance editorSettings.mediaLibrary docs

- guides/image-services.md
PRs
- https://github.com/livingdocsIO/livingdocs-framework/pull/538
- https://github.com/livingdocsIO/livingdocs-server/pull/3410
> Add Doc for Imgix Secure URL Support

- reference-docs/project-config/editor_settings.md
- reference-docs/project-config/media_types.md
Related PR: https://github.com/livingdocsIO/livingdocs-editor/pull/4180
> doc(media library): add doc for computed media library dashboards

- reference/base_filter.md
adds undocumented/added filter options
Related: https://github.com/livingdocsIO/livingdocs-server/pull/3412
> chore: improve base filter docs

- devops/self-hosting.md
Adds a small section on how to avoid CORS
> Small section on how to avoid cors

- reference-docs/includes/server_customization.md
- reference-docs/project-config/settings.md
A summary of the purpose of the `blockEditorInteraction` include config parameter.
> doc(includes): Add interaction blocker details

- guides/add-custom-proofreading-task.md
- Adds docs for this PR https://github.com/livingdocsIO/livingdocs-server/pull/3463
> chore: add 'assignUsers' tasks documentation

- reference-docs/server-configuration/webhooks.md
Add new webhooks according to https://github.com/livingdocsIO/livingdocs-server/pull/3359
> [Release-2021-03] chore: update webhook docs

- reference-docs/editor-configuration/menu-and-dashboards.md
-> https://github.com/livingdocsIO/livingdocs-editor/pull/4244
> doc(main navigation): remove the sidePanelBehavior config docs

- guides/register_custom_dashboard_filters_.md
- reference-docs/project-config/media_types.md
- reference-docs/server-configuration/config.md
- reference/base_filter.md
Add doc for mediaIndex, also with updates for the baseFilters
> Add doc for mediaIndex

- content/enterprise/guides/watching-documents/index.md
We haven't documented how to setup slack app for notifications.
> add slack config documentation

- content/enterprise/reference-docs/server-configuration/single_sign-on.md
Add an openid-connect example for google
> Update openid-connect integration examples

- content/enterprise/reference-docs/editor-configuration/text-editing.md
- content/enterprise/reference-docs/project-config/content-types.md
- content/enterprise/reference-docs/project-config/editor-settings.md
> release-2021-06: Update quotes description and examples

- content/enterprise/reference-docs/project-config/editor-settings.md
- content/enterprise/reference-docs/project-config/media_types.md
Example Config for:
- Editor: https://github.com/livingdocsIO/livingdocs-editor/pull/4500
- Server: https://github.com/livingdocsIO/livingdocs-server/pull/3779
> (dashboard cards): add example config for configured dashboard cards

- content/enterprise/reference-docs/project-config/editor-settings.md
trigger a new version for https://github.com/livingdocsIO/documentation/pull/407
> feat(dashboard cards): extend dashboard card doc and trigger new version

- content/enterprise/reference-docs/editor-configuration/editing-features.md
https://github.com/livingdocsIO/livingdocs-editor/pull/4477
> Remove useAdvancedComponentGroups config setting

- content/enterprise/reference-docs/project-config/notifications.md
Add the comment.resolve action to the notifications feature documentation.
> add comment.resolve to notifications feature

- content/enterprise/reference-docs/editor-api/vue-component-registry.md
- content/enterprise/reference-docs/editor-configuration/default-dashboard-filter.md
- content/enterprise/reference-docs/project-config/editor-settings.md
- content/enterprise/reference-docs/project-config/project-config.md
Documentation for:
- https://github.com/livingdocsIO/livingdocs-editor/pull/4591
- https://github.com/livingdocsIO/livingdocs-server/pull/3876
> feat(document lists): document new configuration possibilities

- content/enterprise/guides/includes/article-and-list-includes/index.md
- content/enterprise/guides/includes/article-list-teasers.md
- content/enterprise/guides/includes/article-teasers.md
Relations:
- Issue: https://github.com/livingdocsIO/livingdocs-planning/issues/4408
- https://github.com/livingdocsIO/livingdocs-server/pull/3846
- https://github.com/livingdocsIO/livingdocs-editor/pull/4556
> feat: Add Article List Teasers page

- redirects.map
- 🐞 Remove self-referencing redirect
> Remove illegal redirect

- content/learn/on-premise-setup.md
- 🎁 Add a checklist for which accounts and services to configure when moving past the evaluation in the 'On Premise Setup' document.
> Add account setup checklist

- content/reference-docs/project-config/content-types.md
Related PRs:
- https://github.com/livingdocsIO/livingdocs-server/pull/3911
- https://github.com/livingdocsIO/livingdocs-editor/pull/4661
> feat: Add document inbox to content type config

- content/operations/releases/release-2021-11/release-2021-11.md
- content/reference-docs/project-config/content-types.md
- content/reference-docs/project-config/editor-settings.md
Add documentation for the new  attributes in CustomElements.
> extend customElements config documentation

- content/guides/documents/document-design/document-design-intro/index.md
- content/guides/documents/metadata/metadata-examples/index.md
- content/guides/editor/document-copy/index.md
- content/guides/editor/image-gallery.md
- content/guides/editor/push-notifications/index.md
- content/guides/media-library/image-services.md
- content/operations/releases/old/release-2017-10.md
- content/reference-docs/document/document-design/_index.md
- content/reference-docs/document/document-design/directives/toggle.md
- content/reference-docs/document/document-design/directives/video.md
- content/reference-docs/document/document-design/legacy-design/design-config-v1.md
- content/reference-docs/document/includes/editor-customization.md
- themes/hugo-docs/layouts/partials/html-header.html
- themes/hugo-docs/layouts/shortcodes/img.html
- 📘 Add `toggle` directive to the reference docs
- 🔧 Cleanup self-closing tags
> Reference: toggle directive

- content/guides/editor/multilist-editor.md
It only works with list teasers with paramsSchema.
> Clarify documentation for multilist editor

- content/reference-docs/project-config/settings.md
- content/reference-docs/server-extensions/server-configuration/_index.md
Relations:
- Issue: https://3.basecamp.com/4910529/buckets/22859585/documents/4511336616
- https://github.com/livingdocsIO/livingdocs-server/pull/4215
- https://github.com/livingdocsIO/livingdocs-editor/pull/5013
Documentation is as detailed as the iMatrics documentation. There are no more in-depth guides.
> feat(retresco): Add config details for Retresco integration

- content/reference-docs/project-config/content-types.md
Relations:
- Issue: https://3.basecamp.com/4910529/buckets/19620057/documents/4315268347
- https://github.com/livingdocsIO/livingdocs-server/pull/4081
- https://github.com/livingdocsIO/livingdocs-editor/pull/4852
> feat: Add media library entry document inbox assignment

- content/reference-docs/server-extensions/webhooks.md
Relations:
- Issue: https://github.com/livingdocsIO/livingdocs-planning/issues/4558
- Related PR's: https://github.com/livingdocsIO/livingdocs-server/pull/4218
> feat: add description for transform webhook request configuration

- content/reference-docs/public-api/beta/latest-draft.md
- content/reference-docs/public-api/beta/latest-publication.md
- content/reference-docs/public-api/beta/latest-publications.md
- content/reference-docs/public-api/composition-api.md
- content/reference-docs/public-api/get-started.md
- content/reference-docs/public-api/publications/latest-publication.md
- content/reference-docs/public-api/publications/latest-publications.md
- content/reference-docs/public-api/publications/renditions.md
- content/reference-docs/public-api/search.md
- 🎁 Add `component` property to example content responses. It got added in `release-2022-03`
> Add component property to examples

- content/reference-docs/server-extensions/server-configuration/storage/_index.md
- 🎁 Document ECS/EKS/Fargate support for the s3 storage config
> Document ECS/EKS/Fargate support in s3 storage config

- content/reference-docs/document/metadata/metadata-plugin-list.md
* li-document-reference
* li-video-reference
> Metadata plugins

- content/reference-docs/document/document-design/directives/video.md
- PR's: https://github.com/livingdocsIO/livingdocs-server/pull/4421
> feat: add `directives` to video example

- content/reference-docs/server-extensions/server-configuration/_index.md
- ✏️  Document custom log formatters in the server configuration
> Reference Docs: custom log formatter server config

- content/reference-docs/server-extensions/include-functions/_index.md
- PR's:  https://github.com/livingdocsIO/livingdocs-server/pull/4439
> feat: add 'remountScripts' config to include functions

- content/guides/media-library/image-services.md
Improve documentation for custom image services
> feat: improve documentation for custom image services

- content/reference-docs/project-config/content-types.md
Relations:
- Related PRs: https://github.com/livingdocsIO/livingdocs-editor/pull/5249
> Document new metadata group behaviour

- content/operations/releases/master/master.md
Added the multi editable selection config to the July release notes to update customers
> fix(master): Add july release config)

- content/reference-docs/document/document-design/directives/link.md
Update documentation for link directive. I now supports the selection of document references as well.
> feat: add document reference for link directive

- content/guides/editor/document-creation-flow.md
- content/reference-docs/project-config/editor-settings.md
PRs
- https://github.com/livingdocsIO/livingdocs-server/pull/4635
- https://github.com/livingdocsIO/livingdocs-server/pull/4606
> Add Documentation for Document Creation Flow

- content/reference-docs/document/metadata/metadata-plugin-list.md
- https://github.com/livingdocsIO/livingdocs-editor/pull/5658
- https://github.com/livingdocsIO/livingdocs-server/pull/4698
> feat(metadata): add li-date type

- content/reference-docs/server-extensions/data-source-api.md
- content/reference-docs/server-extensions/document-version.md
- content/reference-docs/server-extensions/logging.md
- content/reference-docs/server-extensions/project-seeding-api.md
- content/reference-docs/server-extensions/search-customization.md
- content/reference-docs/server-extensions/server-events.md
- content/reference-docs/server-extensions/server-hooks.md
- content/reference-docs/server-extensions/webhooks.md
Add documentation for the Project Seeding Api
Question: As `channels` are going to depreciation, should I add more explanation about how they work?
> feat: add project seeding api

- content/reference-docs/server-extensions/server-configuration/storage/_index.md
Newly added `storage` attribute that allows the users to change their media files path/name with given variables
> feat(computeKey): Add `computeKey()` description

- content/guides/integrations/desknet/index.md
- content/reference-docs/project-config/content-types.md
Relations:
- PR's: https://github.com/livingdocsIO/livingdocs-server/pull/4757
Add config for desknet title sync:
```js
desknet: {
title: {
sync: false
}
}
```
> Add config for desknet title sync

- content/guides/integrations/desknet/index.md
- content/guides/integrations/retresco.md
- content/guides/setup/project-secrets.md
- content/reference-docs/server-extensions/server-configuration/_index.md
Add project secrets guide on how to include secrets and generate new keys with the livingdocs-server utility
> Add project secrets management guide documentation

- content/operations/releases/release-2022-09.md
I saw some broken lists in the release notes and I fixed them in this PR.
> Fix formatting of multiline lists

- content/reference-docs/document/document-design/_index.md
- content/reference-docs/document/document-design/legacy-design/design-config-v1-to-v2.md
Updated the component prefilling docs with example config and component property
> fix(component prefilling): added to design v2

- content/reference-docs/server-extensions/server-configuration/_index.md
Relations:
- PR: https://github.com/livingdocsIO/livingdocs-server/pull/4830
- ♻️ Document new `httpServer` config that got backported to `release-2022-07`
> httpServer config

- content/reference-docs/document/metadata/metadata-plugin-list.md
As suggested, I added further information to the `li-transcoding-state` plugin docs.
> Update `li-transcoding-state` with sample config and release note

- content/guides/media-library/image-services.md
Updated the description on how the config for allowed MimeTypes affects the image services and editor
> fix(mimetypes): Better description

- content/operations/releases/release-2022-11.md
Reordering the highlights for more highlight clarity
> fix(release-2022-11): highlights order

- content/reference-docs/document/metadata/metadata-plugin-list.md
@Muhameti-centralsoft kindly pointed out that we had mixed up the description on these two metadata plugins so this is a small PR to swap them round! 🙏
> Description swapped for base and display filters on metadata plugin list

- content/reference-docs/server-extensions/server-configuration/_index.md
https://github.com/livingdocsIO/livingdocs-server/pull/5191
https://github.com/livingdocsIO/livingdocs-editor/pull/6284
> Document config to anonymize history

- content/guides/authentication/azure-ad-login/index.md
Fix import statement and remove ``alphabet`` parameter since it is invalid. It is ``nanoid(size: number)``.
> update azure sso guide

- content/customising/advanced/editor/browser-api.md
- content/customising/server/document-version.md
- content/guides/integrations/desknet/index.md
- content/guides/integrations/dpa-import.md
- content/reference/document/content/_index.md
- content/reference/public-api/composition-api.md
- content/reference/public-api/get-started.md
- content/reference/public-api/publications/latest-draft-beta.md
- content/reference/public-api/publications/latest-publication-beta.md
- content/reference/public-api/publications/latest-publication.md
- content/reference/public-api/publications/latest-publications-beta.md
- content/reference/public-api/publications/latest-publications.md
- content/reference/public-api/publications/renditions.md
- content/reference/public-api/search.md
- Use remove `identifier` in components where outdated.
- Remove `transmogrifier.wrap()` from documentation
> Update identifier references

- content/operations/releases/release-2023-03.md
- No homescreen
- No SMB focal point
> Remove wrong release-2023-03 notes

- content/customising/back-to-standard/metadata-plugins.md
- content/operations/releases/release-2023-03.md
Add anonymize description and links to release notes and fix duplicated title in pages
> Anonymize release notes

- content/guides/integrations/retresco.md
Extend explanation for `/re-enrich` endpoint and `enrichConcurrency` configuration option
> Add new `enrichConcurrency` configuration option

- content/reference/project-config/content-types.md
https://github.com/livingdocsIO/livingdocs-editor/pull/6738
> Metadata previews

- content/operations/releases/release-2023-05.md
I have added the vulnerabilities fixed in this release and pointed to the vulnerability report as I think it is more interesting than our PR upgrading the module in `package.json` or `package-lock.json`
> Add information on fixed vulnerabilities in May release

- content/reference/project-config/content-types.md
- 🎁 Add contentType config dragPreviewDelay
- 💎 Fix some other contentType config descriptions.
> Add contentType.editor.dragPreviewDelay

- content/customising/server-configuration/_index.md
Relations:
- Issue: https://3.basecamp.com/4910529/buckets/30100218/todolists/5780864130
- Related PR: https://github.com/livingdocsIO/livingdocs-server/pull/5626
> Add document.realtimeUpdates to server config

- content/reference/document/includes/server-customization.md
Addition from previous PR: https://github.com/livingdocsIO/documentation/pull/667
> fix(paramschema): slight text change

- content/customising/server-configuration/_index.md
- content/guides/editor/document-previews/index.md
- https://github.com/livingdocsIO/livingdocs-server/pull/5786
- https://github.com/livingdocsIO/livingdocs-editor/pull/6978
> feat: add guide for document previews

- content/guides/editor/document-copy/index.md
- content/operations/releases/release-2023-07.md
Add documentation update for copy target label and icon config
Related PRs: https://github.com/livingdocsIO/documentation/pull/651
> Add documentation update for copy target label and icon config

- content/operations/releases/release-2023-07.md
Please:
* Assign the right person in case you are the wrong assignee for the topic
* Follow [these instructions](https://github.com/livingdocsIO/documentation/pull/682/files#diff-f91e6cce1a1ad58ee67f7939ede1526a4c5ee7bfb758e9584591b0b8820b86a0R30) (input on how to make them more precise / accurate are very welcome)
* add or remove topics which are / are not relevant for the tech release notes
* move your feature to the fitting section (breaking changes, feature, improvement, etc.)
* Add short description and config example
* Add linke to detailed documentation
* Please commit any changes directly to this PR or leave a comment/change request so Jordi and I can add the change. This way it's more likely that we can avoid merge conflicts.
Please also have a look at all your PRs which you've …
> Tech release notes - release-2023-07

- content/reference/document/metadata/metadata-plugin-list.md
Added the compatibility for li-string-list to li-push-messages paramsSchema
> fix(push messages): li string list added

- content/operations/releases/release-2023-07.md
I added the links to the relevant PRs and updated the description to be clearer on what the bug was for each PR.
> Release Note Bugfixes Information added

- content/reference/public-api/drafts/incoming-references.md
- 🖊️ Add incoming draft references endpoint to the reference docs
> feat: add incoming draft references api endpoint

- content/operations/releases/release-2023-07.md
- content/reference/document/metadata/metadata-plugin-list.md
@JordiVM I removed the language display filter thingy from the release notes page and added a few words on that in the li-tree multi-lang docs.
> Update release-2023-07 notes for li-tree

- content/customising/server-configuration/_index.md
> Document `import.allowCustomIdsBelow`

- content/operations/releases/release-2023-07.md
Relations:
- Related PRs:
- https://github.com/livingdocsIO/documentation/pull/673
- https://github.com/livingdocsIO/livingdocs-server/pull/5744
> Update release-2023-07 with Public API Search Filters explanation

- content/operations/releases/release-2023-07.md
- Add links to release-2023-07 release notes
> Add links to release-2023-07 release notes

- content/guides/documents/includes/document-teasers.md
- content/guides/documents/includes/editable-document-teasers.md
- content/guides/editor/author-management/index.md
- content/guides/editor/image-gallery.md
- content/operations/releases/release-2023-09.md
- content/reference/document/metadata/plugins/li-document-reference.md
- content/reference/document/metadata/plugins/li-document-references.md
- content/reference/document/metadata/plugins/li-reference-list.md
- content/reference/document/metadata/plugins/li-reference.md
- content/reference/document/references/_index.md
- content/reference/project-config/content-types.md
- content/reference/project-config/editor-settings.md
- content/reference/public-api/composition-api.md
Relations:
- Issue: https://3.basecamp.com/4910529/buckets/31157489/todos/6290750294
- Related PRs:
- https://github.com/livingdocsIO/livingdocs-server/pull/6030
- https://github.com/livingdocsIO/livingdocs-editor/pull/7274
> Replace li-reference(-list) with li-document-reference(s)

- content/guides/media-library/image-services.md
While working on our own image service I noticed a couple of places where the documentation might be improved slightly. Either by finishing a sentence ;), providing a link or rewording something slightly differently.
Let me know what you think, happy to address any feedback!
> fix(image-services): revise image services guides

- content/operations/releases/release-2023-09.md
- content/operations/releases/release-2023-11.md
Includes new file for `release-2023-11`
> Technical release notes for `release-2023-09`

- content/operations/releases/release-2023-09.md
Related PRs: https://github.com/livingdocsIO/documentation/pull/725
I want to address some of the comments that we didn't address in the related PR. Specifically: https://github.com/livingdocsIO/documentation/pull/725#discussion_r1305135610
> Improvements TRN release-2023-09

- content/reference/public-api/health.md
- content/reference/public-api/retresco.md
Include re-enrich endpoint to Public API documentation.
> Add retresco re-enrich endpoint to the public API documentation

- content/reference/public-api/publications/search.md
> fix(typo): dafault to default

- content/customising/server/server-hooks.md
- content/guides/documents/document-design/data-migrations/index.md
- 🔧 Remove render hooks
- 🔧 Small wording improvements for migrations
> Random updates

- content/guides/search/publication-index-legacy.md
- content/reference/document/metadata/plugins/li-reference-list.md
- content/reference/document/metadata/plugins/li-reference.md
- content/reference/project-config/content-types.md
- content/reference/project-config/editor-settings.md
Relations:
- Related PRs: https://github.com/livingdocsIO/livingdocs-server/pull/6186
> Add removed-in tag to `li-reference` and `li-reference-list` metadata plugins

- content/operations/releases/release-2023-11.md
https://github.com/livingdocsIO/livingdocs-editor/pull/7655
https://github.com/livingdocsIO/livingdocs-server/pull/6268
> Add simple search enable configuration to November release notes

- README.md
- content/operations/releases/release-2023-11.md
- themes/hugo-docs/assets/elements/feature-info.scss
- themes/hugo-docs/assets/elements/highlight.scss
- themes/hugo-docs/assets/style.scss
- themes/hugo-docs/layouts/shortcodes/feature-info.html
- 🎁 Add `feature-info` shortcode
- Use feature-info shortcode for technical release notes in November release
> Technical release notes improvements / Feature info shortcode

- content/operations/releases/release-2023-11.md
> Add API changes to November release notes

- content/customising/advanced/editor-configuration/editing-features.md
- content/customising/advanced/editor/document-drag-drop.md
- content/guides/documents/document-design/document-design-intro/add-component-patch.patch
- content/guides/documents/document-design/document-design-intro/add-default-content.patch
- content/guides/documents/document-design/document-design-intro/index.md
- content/guides/documents/metadata/metadata-examples/index.md
- content/guides/editor/push-notifications/index.md
- content/guides/setup/server-customization.md
- content/learn/drafts/getting-started.md
- content/operations/docker.md
- content/operations/npm-packages.md
- content/operations/on-premise-setup.md
- content/reference/document/content/_index.md
- content/reference/document/includes/editor-customization.md
- content/reference/document/metadata/plugins/li-push-messages.md
- content/reference/project-config/content-types.md
- 🔧 Remove links to the now archived editor and server boilerplate repos
> Remove boilerplates

- content/reference/document/metadata/plugins/li-ticker-host-reference.md
> li-ticker-host-reference plugin docs

- content/customising/server-configuration/_index.md
- content/operations/releases/release-2023-11.md
I've updated the Server Configuration and Technical Release Notes with some details from the Dev Webinar.
> Add more details about real-time teaser includes

- content/operations/releases/old/release-2018-11.md
- content/operations/releases/old/release-2019-01.md
- content/operations/releases/old/release-2019-03.md
- content/operations/releases/old/release-2019-05.md
- content/operations/releases/old/release-2019-07.md
- content/operations/releases/old/release-2019-09.md
- content/operations/releases/old/release-2019-12.md
- content/operations/releases/old/release-2020-02.md
- content/operations/releases/old/release-2020-04.md
- content/operations/releases/old/release-2020-05.md
- content/operations/releases/old/release-2020-07.md
- content/operations/releases/old/release-2020-10.md
- content/operations/releases/old/release-2020-12.md
- content/operations/releases/release-2021-03.md
- content/operations/releases/release-2021-06.md
- content/operations/releases/release-2021-09.md
- content/operations/releases/release-2021-11.md
- content/operations/releases/release-2022-03.md
- content/operations/releases/release-2022-07.md
- content/operations/releases/release-2022-09.md
- content/operations/releases/release-2022-11.md
- content/operations/releases/release-2023-01.md
- content/operations/releases/release-2023-03.md
- content/operations/releases/release-2023-05.md
- content/operations/releases/release-2023-07.md
- content/operations/releases/release-2023-09.md
- content/operations/releases/release-2023-11.md
- content/operations/releases/release-2024-01.md
As mentioned in the team meeting, we should clarify the behaviour when rolling out the new release and the migrations side effects.
> Add information to migrations for november release

- content/guides/editor/custom-dashboard-filters/index.md
Relations:
- Related PR: https://github.com/livingdocsIO/livingdocs-server/pull/6406
> Add note about emitting a single object from custom filters

- content/customising/server-configuration/_index.md
Relations:
- Issue: Fixes https://github.com/livingdocsIO/livingdocs-bugs/issues/5104
> Add note explaining realtime updates websockets setup with HTTPS

- content/guides/media-library/media-library-setup/index.md
Relations:
- Issue: https://3.basecamp.com/4910529/buckets/33816083/documents/6869025355
- Server PR: https://github.com/livingdocsIO/livingdocs-server/pull/6530
- Editor PR: https://github.com/livingdocsIO/livingdocs-editor/pull/7955
- Framework PR: https://github.com/livingdocsIO/livingdocs-framework/pull/976
- Clarify the dependencies of the components that support Named Crops.
- Provide more extensive documentation for the existing configuration properties.
- Introduce and describe the new `isDefaultIfSet` configuration property.
> feat(named-crops): Clarify Named Crops documentation and add isDefaultIfSet property

- content/guides/documents/includes/document-teasers.md
- content/guides/editor/document-creation-flow.md
- content/reference/document/metadata/plugins/li-buy-in.md
- content/reference/project-config/editor-settings.md
Updated some config examples where the old filter syntax was still used.
> Use new filter dsl in examples

- content/operations/releases/release-2024-03.md
> Extend release notes with improvements

- content/operations/releases/release-2024-03.md
- content/reference/document/metadata/plugins/li-datetime-validity.md
- content/reference/document/metadata/plugins/li-invalid.md
- content/reference/webhooks/_index.md
Relations:
- Issue: https://3.basecamp.com/4910529/buckets/33816083/todos/6797437693
- Related PR:
- https://github.com/livingdocsIO/livingdocs-server/pull/6629
- https://github.com/livingdocsIO/livingdocs-server/pull/6653
- https://github.com/livingdocsIO/livingdocs-editor/pull/8090
- https://github.com/livingdocsIO/livingdocs-editor/pull/8140
> Media Library Scheduler

- content/customising/advanced/server-events.md
Relations:
- https://github.com/livingdocsIO/documentation/pull/807
- Issue: https://3.basecamp.com/4910529/buckets/33816083/todos/6797437693
- https://github.com/livingdocsIO/livingdocs-server/pull/6629
- https://github.com/livingdocsIO/livingdocs-server/pull/6653
- https://github.com/livingdocsIO/livingdocs-editor/pull/8090
- https://github.com/livingdocsIO/livingdocs-editor/pull/8140
- https://github.com/livingdocsIO/livingdocs-server/pull/6658
> Add publication.update to server events

- content/customising/advanced/server-events.md
Relations:
- Issue: https://3.basecamp.com/4910529/buckets/33816083/todos/6797437693
- Related PRs:
- https://github.com/livingdocsIO/documentation/pull/808
- https://github.com/livingdocsIO/documentation/pull/807
- https://github.com/livingdocsIO/livingdocs-server/pull/6629
> Add missing server events

- content/operations/releases/release-2024-03.md
- content/reference/project-config/content-types.md
- content/reference/public-api/composition-api.md
- content/reference/public-api/document-lists.md
- content/reference/public-api/drafts/latest-draft-beta.md
- content/reference/public-api/publications/latest-publication-beta.md
- content/reference/public-api/publications/latest-publication.md
- content/reference/public-api/publications/latest-publications-beta.md
- content/reference/public-api/publications/latest-publications.md
- content/reference/public-api/publications/renditions.md
- content/reference/public-api/publications/search.md
Relations:
- Issue: https://3.basecamp.com/4910529/buckets/33816083/todolists/6637796452
- Related PRs:
- https://github.com/livingdocsIO/livingdocs-server/pull/6523
- https://github.com/livingdocsIO/livingdocs-editor/pull/7947
- https://github.com/livingdocsIO/livingdocs-framework/pull/969
> Conditional Components

- content/operations/releases/release-2024-03.md
- content/reference/project-config/content-types.md
Relations:
- Related PR: https://github.com/livingdocsIO/documentation/pull/812
> Add webhook payload example to conditional components release notes

- content/customising/angular-migration/metadata-plugins.md
- content/customising/server/server-api/public-api.md
- content/guides/search/publication-index.md
- content/reference/public-api/publications/latest-publications-beta.md
- content/reference/public-api/publications/latest-publications.md
- content/reference/public-api/publications/search.md
* Public API LatestPublications
* 🍬 Improve doc (offset max 10000, use range queries)
* 🍬 Make limit/offset less prominent
* Server Public API doc (search + latest publications)
* ♻️ Move search API doc from guide to reference doc
* 🍬 Add some examples
> Public API doc improvements

- content/reference/document/metadata/plugins/li-issue-management.md
- content/reference/project-config/_index.md
- content/reference/project-config/finite-products.md
* ✏️ Add `finiteProducts` to the project config reference docs.
> Add finite-products documentation

- content/customising/advanced/editor-configuration/display-filter.md
- content/reference/document/metadata/plugins/li-imatrics-nlp-tags.md
Relations:
- Issue: https://3.basecamp.com/4910529/buckets/33963114/documents/7057835529
- Server PR: https://github.com/livingdocsIO/livingdocs-server/pull/6749
- Editor PR: https://github.com/livingdocsIO/livingdocs-editor/pull/8294
> Add iMatrics display filter support

- content/guides/integrations/hugo-dnd/index.md
- content/reference/project-config/media-types.md
* ✏️ Add missing `hugoExtraction` docs.
> Add hugoExtraction docs

- themes/hugo-docs/assets/search.js
* 🐞 Clean up text before it is indexed by lunr. This fixes a bug where any text directly adjacent to html tags would not be indexed (e.g. links, inline code blocks, most code).
> 🐞Fix search indexing

- content/customising/advanced/editor-configuration/display-filter.md
- content/reference/document/metadata/plugins/li-retresco.md
Relations:
- Issue: https://3.basecamp.com/4910529/buckets/33963114/documents/7057835529
- Server PR: https://github.com/livingdocsIO/livingdocs-server/pull/6795
- Editor PR: https://github.com/livingdocsIO/livingdocs-editor/pull/8343
> Retresco display filter support

- content/customising/advanced/editor/vue-component-registry.md
- content/guides/editor/custom-table-dashboard-cells.md
I recently had to implement a custom table cell for Handelsblatt and saw a couple of things in the docs which were not correct.
> Custom table cell fixes

- content/customising/advanced/editor-configuration/editing-features.md
Related: https://github.com/livingdocsIO/livingdocs-editor/pull/8362
> Update Keyboard Shortcuts

- content/operations/releases/release-2024-05.md
First clean up for release-2024-05.
> Clean up PRs to categorize and add all relevant sections for release-2024-05

- content/operations/releases/release-2024-07.md
- data/releases.json
To be merged during release cut meeting.
> Add July release notes to documentation during release-management

- content/guides/documents/document-lifecycle/_index.md
- content/guides/documents/document-lifecycle/restore-a-document/index.md
* 💎 Add a guide on how to restore documents.
> Add document restore guide

- content/guides/editor/proofreading-dashboard.md
Relations:
- Editor PR: https://github.com/livingdocsIO/livingdocs-editor/pull/8392
> Replace Angular dashboard card with Vue dashboard card

- content/guides/documents/document-design/data-migrations/index.md
We recently received a heads-up from Joe about writing tests for migrations. He provided an example, and I thought it might be helpful for others too.
As always, feedback is welcome.
> docs: adds example for migration test

- content/operations/releases/release-2024-05.md
- content/reference/document/metadata/plugins/li-manual-document-status.md
Add description for the manual document status
> Add manual document status feature description

- content/operations/releases/release-2024-05.md
Adds the description for the improvements of the simple document search.
> Add document search improvements description

- content/guides/integrations/desknet.md
Relations:
- Issue: https://github.com/livingdocsIO/livingdocs-bugs/issues/5271
- Related PR: https://github.com/livingdocsIO/livingdocs-server/pull/7019
> Add userId to parameters of Desk-Net Global functions

- content/operations/releases/release-2024-01.md
- content/operations/releases/release-2024-03.md
- content/operations/releases/release-2024-05.md
- content/operations/releases/release-2024-09.md
Update vulnerability patches in January to July release notes, create september release notes page, clean up July release notes.
> Release preparation, cleanup of release notes

- content/operations/releases/release-2024-07.md
- https://github.com/livingdocsIO/livingdocs-server/pull/6970
- https://github.com/livingdocsIO/livingdocs-editor/pull/8599
> Add offline mode improvements to release notes

- content/operations/releases/release-2024-07.md
Documentation:
- https://github.com/livingdocsIO/documentation/pull/864
Code:
- https://github.com/livingdocsIO/livingdocs-server/pull/6923
- https://github.com/livingdocsIO/livingdocs-editor/pull/8517
- https://github.com/livingdocsIO/livingdocs-server/pull/6965
- https://github.com/livingdocsIO/livingdocs-editor/pull/8585
- https://github.com/livingdocsIO/livingdocs-server/pull/7024
- https://github.com/livingdocsIO/livingdocs-editor/pull/8651
- https://github.com/livingdocsIO/livingdocs-server/pull/7046
- https://github.com/livingdocsIO/livingdocs-editor/pull/8679
> Add Delivery Builds User Choices to release notes

- content/operations/releases/release-2024-07.md
- data/releases.json
> Introduce September release to releases list

- content/guides/integrations/desknet.md
Relations:
- Related PR: https://github.com/livingdocsIO/livingdocs-server/pull/7058
> Add `projectConfig` to Desk-Net functions

- content/operations/releases/release-2024-07.md
Take deprecation text from Comyan to a feature section. It makes more clear what is actually being deprecated.
> Separate Comyan deprecation and feature

- content/reference/project-config/settings.md
Server PR: https://github.com/livingdocsIO/livingdocs-server/pull/7157
> Add iMatrics testEnvironment config property

- content/guides/integrations/retresco.md
- content/reference/document/metadata/plugins/li-retresco.md
Server PR: https://github.com/livingdocsIO/livingdocs-server/pull/7164
> Add support for Retresco main entities

- content/operations/releases/release-2024-09.md
- content/reference/document/metadata/plugins/li-document-reference.md
- content/reference/document/metadata/plugins/li-document-references.md
Relations:
- Issue: https://3.basecamp.com/4910529/buckets/37094860/documents/7449082131
- Documentation: https://github.com/livingdocsIO/documentation/commit/b24905a87c7e6e9fd486968c5561111c61db45de
- Related PRs:
- https://github.com/livingdocsIO/livingdocs-server/pull/7159
- https://github.com/livingdocsIO/livingdocs-editor/pull/8880
> Add cacheSearch property to document reference plugins

- content/customising/server/server-hooks.md
- content/operations/releases/release-2024-09.md
I've added a note on how to refactor code with new validation errors, after struggling a bit myself when implementing it for 20min.
> fix: add some details on new validation errors

- content/operations/releases/release-2024-11.md
- content/reference/document/metadata/plugins/li-task-v2.md
Relations:
- https://github.com/livingdocsIO/livingdocs-server/pull/7331
- https://github.com/livingdocsIO/livingdocs-editor/pull/9059
- https://github.com/livingdocsIO/livingdocs-server/pull/7421
- https://github.com/livingdocsIO/livingdocs-editor/pull/9130
> Add documentation for li-task-v2 improvements

- content/guides/editor/document-print-flows.md
- content/operations/releases/release-2024-11.md
- content/reference/project-config/content-types.md
- content/reference/project-config/editor-settings.md
Relations:
- Issue: https://3.basecamp.com/4910529/buckets/37094860/todolists/7401830778
- Related PRs:
- https://github.com/livingdocsIO/livingdocs-server/pull/7158
- https://github.com/livingdocsIO/livingdocs-editor/pull/8829
- Guide created
- Project config reference document updated
- Content type config reference document updated
- Release notes updated
> Document Print Flows

- content/reference/project-config/content-types.md
- content/reference/project-config/settings.md
Relations:
- Issue: https://3.basecamp.com/4910529/buckets/37243508/todolists/7710117128
- Related PRs:
- https://github.com/livingdocsIO/documentation/pull/915
- https://github.com/livingdocsIO/livingdocs-server/pull/7322
- https://github.com/livingdocsIO/livingdocs-editor/pull/9047
> Add videoSourcePolicy to reference docs

- Dockerfile
- themes/hugo-docs/layouts/index.searchindex.json
- themes/hugo-docs/layouts/partials/html-header.html
- Use newest Hugo version in CI
- Fix Hugo deprecations
> Fix Hugo deprecations

- content/customising/server-configuration/_index.md
- content/operations/releases/release-2025-01.md
- content/reference/project-config/settings.md
- add release notes for peiq drag & drop integration
> Add peiq release info

- content/operations/releases/release-2025-01.md
- content/reference/document/document-design/directives/editable.md
- add deprecation notice for whitelist and blacklist
> deprecate blacklist and whitelist for denylist and allowlist

- content/operations/releases/release-2024-09.md
- content/operations/releases/release-2024-11.md
- content/operations/releases/release-2025-01.md
Added vulnerability patches for the latest releases and remove Product analytics from the release notes page
> Add vulnerabilities patched and clean up January release page

- content/operations/releases/release-2025-01.md
- Print Diff View
- Document preview auto-reload
- Real-time updates enabled by default
> Add remaining release-2025-01 feature details

- content/operations/releases/release-2025-01.md
Relations:
- Related PR: https://github.com/livingdocsIO/documentation/pull/953
> Add note on when (not) to use auto-reload in release-2025-01 releasse notes

- content/guides/editor/document-print-flows.md
Relations:
- Related PRs:
- https://github.com/livingdocsIO/livingdocs-demo/pull/460
- https://github.com/livingdocsIO/livingdocs-server/pull/7640
> Add warning about missing or random component ids in print flow function output

- content/reference/document/metadata/plugins/li-kordiam-global.md
- content/reference/document/metadata/plugins/li-kordiam-integration.md
- content/reference/document/metadata/plugins/li-kordiam-schedule.md
- content/reference/public-api/composition.yaml
- content/reference/public-api/document-lists/get_list_by_id.yaml
- content/reference/public-api/document_commands.yaml
- content/reference/public-api/drafts/latest-draft-beta.yaml
- content/reference/public-api/publications/get_latest_publication.yaml
- content/reference/public-api/publications/get_latest_publication_beta.yaml
- content/reference/public-api/publications/latest_publications.yaml
- content/reference/public-api/publications/latest_publications_beta.yaml
- content/reference/public-api/publications/publication_renditions.yaml
- content/reference/public-api/publications/search_publications.yaml
- themes/hugo-docs/assets/elements/api-example.scss
- themes/hugo-docs/layouts/metadata-plugins/single.html
- themes/hugo-docs/layouts/partials/added-in.html
- themes/hugo-docs/layouts/partials/default-below-content--metadata-plugins.html
- themes/hugo-docs/layouts/release-notes/single.html
- themes/hugo-docs/layouts/shortcodes/api-example-resource.html
> Add history table support to endpoints and metadata plugins

- content/operations/releases/release-2025-03.md
Related PRs:
- https://github.com/livingdocsIO/livingdocs-server/pull/7794
> Data migrations migrate scheduled publications

- content/reference/project-config/content-types.md
- content/reference/project-config/editor-settings.md
Add general documentation on Smart Quotes
> Release 2025 03/add smart quotes

- content/reference/public-api/_index.md
- data/endpoints/import-files-status.yaml
- data/endpoints/import-files.yaml
- data/endpoints/import-images-status.yaml
- data/endpoints/import-videos-status.yaml
- data/endpoints/media-library-serve-image.yaml
- themes/hugo-docs/layouts/_default/single.html
- themes/hugo-docs/layouts/partials/openapi-template.gotmpl
- themes/hugo-docs/layouts/shortcodes/openapi.html
Relations:
- Server PR: https://github.com/livingdocsIO/livingdocs-server/pull/7857
> Fix import documentation

- content/operations/releases/release-2025-03.md
After the incident with Netcetera, we want to clearly define the steps in the deployment to ensure it doesn't happen again.
> Define Deployment steps with check for manual migration

- content/operations/releases/release-2025-05.md
Adds documentation for:
- table dashboard cells
- clipboard context
- clickable title for teaser sidebars
> Release 2025-05

- content/operations/releases/release-2025-05.md
- content/reference/public-api/changelog/2025-05/kordiam-rebranding-remove-desknet-endpoints.md
- Add desknet > kordiam url changes to public api changelog & release notes
> Mention Kordiam Rebranding in Public API Changelog

- content/guides/media-library/media-library-setup/index.md
- content/operations/releases/release-2025-05.md
> Clarify image editing documentation

- content/operations/releases/release-2025-03.md
- content/operations/releases/release-2025-05.md
- content/operations/releases/release-2025-07.md
- Format release rollout deployment sections and compatibility tables
- Fix feature-info sections on May 2025 release
> Refactor latest releases to match standard

- content/reference/public-api/changelog/2025-05/menu-tool-removal.md
- data/endpoints/get-menus.yaml
- themes/hugo-docs/layouts/partials/api-example-resource.html
- https://github.com/livingdocsIO/livingdocs-server/pull/7838
- https://github.com/livingdocsIO/livingdocs-editor/pull/9714
> Add documentation for removal of Menu Tool to Public API

- content/operations/releases/release-2025-03.md
- content/reference/document/metadata/plugins/li-document-reference.md
- content/reference/document/metadata/plugins/li-document-references.md
- content/reference/document/metadata/plugins/li-teaser.md
- content/reference/document/migration/on-read-migration.md
- Clarify on-read migrations guide
- Explain filter configuration behavior with useDashboard
> On-read migrations clarification

- content/operations/releases/release-2025-07.md
Relations:
- Related PR: https://github.com/livingdocsIO/livingdocs-server/pull/8193
> Use new populate-reference-ids command

- content/guides/media-library/2025-behavior/index.md
- content/operations/releases/release-2025-07.md
Relations:
- Related PR: https://github.com/livingdocsIO/livingdocs-server/pull/8224
> Add additional warning for deletion routines
