design/create_designs.md
A comma was missing in the example.
=> add missing comma in example

delivery/api_essentials.md, delivery/webhooks.md, server/public_api_endpoints.md
Describe the new fields `metadata` and `design` on the public API and mark `data` as deprecated.
Merge this PR with the next production release.
=> Update public api

core/guides/local-development/editor-only.md
Splits command and makes more generic.
=> docs(editor-only): fix commands

README.md, contribution-guidelines/ramp-up/html.md, contribution-guidelines/ramp-up/javascript.md
@peyerluk This was a PR on the now gone upfrontIO/guides. All the content of that repo is now in this one.
=> docs: js and HTML ramp-up

contribution-guidelines/style-guides/naming.md
Branch from RIP upfrontIO/guides
=> docs(guidelines): naming conventions

contribution-guidelines/style-guides/scss.md
Related to https://github.com/upfrontIO/livingdocs-planning/issues/365
This is what I have done:
* Provided more details on the CSS structure, BEM naming / nesting and state rules
* Added `ld-` prefix rule
* fixed some spelling erros
Shout-out to @manufaktor for supporting me on my quest to improve the CSS guide. 🕺
=> Update CSS guide

reference-docs/server-print-api/print-api.md
Docu for https://github.com/upfrontIO/livingdocs-editor/pull/1499
=> feat(print): Add config section with print preview default mode.

reference-docs/server-extensions/add-custom-include.md
Document what to return in an include renderer when the params are insufficient so that the editor displays no errors and still displays the preview. Also try to fill in missing parts in the docs and try to clarify the use cases by restructuring the docs.
=> fix(server-extensions): rework include documentation

SUMMARY.md, concepts/images/image-services.md, concepts/images/why-an-image-service.md, reference-docs/common-designs/component_config.md, reference-docs/server-configuration/config.md, reference-docs/server-editing-api/README.md, reference-docs/server-print-api/print-api.md, reference-docs/server-public-api/public-api.md, setup-and-deployment/deployment/container/docker.md, setup-and-deployment/npm/publish-packages.md, videos/design_intro.md, walkthroughs/add_customizations.md
Markdown headings are specified as `#<space+><name>`. This PR changes all `#<nspb><name>` to replace the nbsp with a space in order to have these parsed as titles instead of literal `# foo`.
=> chore(docs): Remove nbsp in Markdown titles

reference-docs/server-configuration/metadata.md
@DaRaFF fyi people tend to just copy sample code so the sample code should never "break" stuff. We had the problem with somebody just copying the code and then wondering why all metadata fields became `null` after saving.
=> Add return statement to metadata plugin examples

SUMMARY.md, reference-docs/server-extensions/hugo-dnd.md
This is my initial draft on the hugo drag and drop documentation. A couple of questions:
* ~What's the difference between agency and archive articles? There's an API documentation on hugo APIs. Unfortunately I could not find anything meaningful about those two types.~
* ~[This](https://github.com/nzzdev/livingdocs-api/blob/0afc4680eed6bf5c96131804ad154aa6460109b9/plugins/hugo-import-transformations/agency/util/transform.js#L5) - Does it have to be _resrc.it_?~
* ~The customers using this feature need the metadata plugin too, right?~
=> Add documentation on Hugo Drag and Drop

SUMMARY.md, reference-docs/editor-configuration/editing-features.md
Document configuration of _Transform Component_ visibility.
Issue: upfrontIO/livingdocs-planning#1632
PR: https://github.com/upfrontIO/livingdocs-editor/pull/1793
=> Configure visibility of the Transform Component

reference-docs/editor-configuration/editing-features.md
We introduce changes in the transform component configuration. Now users can show the transform component dropdown **even** if there is no transformations available.
See: https://github.com/upfrontIO/livingdocs-editor/pull/1862
@daut-morina can you review?
=> docs: extend transform component configuration

administration/access_rights.md, reference-docs/editor-configuration/editing-features.md, reference-docs/editor-configuration/search-filters.md
Server PR https://github.com/upfrontIO/livingdocs-server/pull/1879
This PR adds the documentation of the new scopes, menues and filters needed for the new document-type `data`.
=> Data Dashboard v1

reference-docs/editor-configuration/search-filters.md
see:
- PR https://github.com/upfrontIO/livingdocs-editor/pull/1939
- Issue https://github.com/upfrontIO/livingdocs-planning/issues/1622
This adds documentation for empty search queries.
=> chore(search-filters): add empty search queries documentation

reference-docs/server-configuration/content-type-config.md
Documentation for: https://github.com/upfrontIO/livingdocs-editor/pull/2002
=> docs(content-type-config): add documentation for editor ui

reference-docs/server-configuration/config.md, reference-docs/server-configuration/single_sign-on.md
https://github.com/upfrontIO/livingdocs-planning/issues/2011
Auth configuration before:
```
auth: {
connections: {
foo: {
enabled: true
}
}
}
```
Auth configuration after:
```
auth: {
connections: {
foo: {
enabled: true,
loginEnabled: true,
registrationEnabled: true,
}
}
}
```
=> docs: multiply auth connections toggle flags

reference-docs/server-configuration/content-type-config.md
Related:
- https://github.com/livingdocsIO/livingdocs-server/pull/2140
- https://github.com/livingdocsIO/livingdocs-editor/pull/2370
=> Add disableEditTitleAtToolbar flag to the content-type config

walkthroughs/getting-started-with-local-development.md
Not listed in, but still addressing livingdocsIO/livingdocs-planning#2549
=> Fix link to windows10 setup guide

README.md, dev_readme.md
Info how to build and deploy the documentation should not be part of the documentation for customers.
=> Move info for documentation maintainers out of the readme

SUMMARY.md, reference-docs/common-designs/create_designs.md, reference-docs/server-configuration/admin-commands.md, walkthroughs/metadata/metadata-examples.md
Reorganisation of the main Navigation. The main focus was on the reference documentation and to indicate the context of the different docs better. Also I tried to separate Concepts/Guides from Howtos. And a few small things like Title Casing all the links and renaming some entries.
This PR is best to review locally by running `gitbook serve` and checking out what you like, don't like in the navigation.
=> Reorganisation of the navigation

reference-docs/doc-includes/intro.md
- Before: ![](http://screenshots.200ok.ch/screenshot_2019_02_21-6cd4344e.png)
- After: ![](http://screenshots.200ok.ch/screenshot_2019_02_21-4218692a.png)
=> fix: Styling for doc-include example

SUMMARY.md, concepts/document-migrations/examples/add_metadata_field.md, concepts/document-migrations/examples/remove_directive.md, concepts/document-migrations/examples/rename_directive.md, concepts/document-migrations/migrations.md
Issue: https://github.com/livingdocsIO/livingdocs-planning/issues/2418
We want to remove the data migration examples from the boilerplate and instead have the examples within our enterprise documentation
This should be merged first: https://github.com/livingdocsIO/livingdocs-server-boilerplate/pull/132
=> Add data-migration examples to the enterprise documentation 

concepts/images/image-services.md, reference-docs/server-configuration/config.md
We changed the image service selection from editor-side to server-side: https://github.com/livingdocsIO/livingdocs-planning/issues/2536
This PR documents the changes.
Other changes documented:
- make clear that DAM needs `liImageProxy`
- moved `paginationSize` from `liImageProxy` to `assetManagment`
- introduced `proxiedImageService` in `liImageProxy`
=> Document `selectedImageService

reference-docs/server-configuration/hooks.md
We've removed it in the following commit as it wasn't used anywhere https://github.com/livingdocsIO/livingdocs-server/commit/d42b1882722e821dddfda8d514a7c89264ba1650#diff-d22eff43244cf5e060b2f23236a5b1b4
=> Remove the `getExternalList` hook as we don't support it anymore

reference-docs/editor-configuration/text-editing.md
Issue: https://github.com/livingdocsIO/livingdocs-planning/issues/2681
Editor-PR: https://github.com/livingdocsIO/livingdocs-editor/pull/2697
Alongside with extending our current link behavior with default configs, the documentation needs to showcase the configs as well.
=> feat(links): extend documentation for links

walkthroughs/add-custom-proofreading-task.md
Related PRs: https://github.com/livingdocsIO/livingdocs-editor/pull/2787
- add `linkToDashboard ` config property for `li-task-v2` metadata plugin
=> Additional documentation for tasks

reference-docs/editor-configuration/editing-features.md
We doesn't support `diffViewEnabled` anymore. So we had to remove it from the documentation.
=> update differ config

concepts/copying-documents/document_copy_feature.md
- Issue: https://github.com/livingdocsIO/livingdocs-planning/issues/2999
Adds a small example about copying/excluding all components without instructions
=> Document copy add example about matching

reference-docs/server-configuration/config.md
Since heute.at had some issues getting the emails to work, let's add what ended up working for them to our documentation.
=> Email-configs: add httpOption config

reference-docs/editor-configuration/image-source-policy.md, reference-docs/server-configuration/content-type-config.md
Server PRs:
- `release-2019-09` https://tracking.nzzmg.ch/browse/WCMS-4663
- `master`
Editor PRs:
- `release-2019-09` https://github.com/livingdocsIO/livingdocs-editor/pull/3090
- `master`
Note the new `editor.images.sourcePolicy` contentType setting is a superset of the current `editor.images.whitelist`, therefore `whitelist` will be deprecated.
=> docs: Add `contentType` specific image `sourcePolicy`

walkthroughs/getting_started.md
Due to the inline design workflow making design and metadata changes is super simple now. We should hide the in-depth sections about the design and let the user experience the inline design at first.
=> Improve getting started section

SUMMARY.md, livingdocs-cli/cli-dotfile.md, livingdocs-cli/sync-configs.md
- Add docs how to set up a `.livingdocs-cli` file
- Describe config sync process with the CLI
- Add those to the main navigation
=> fix(cli): add docs for config-sync workflow

reference-docs/server-configuration/channel-config.md
This adds a basic example for `includeServices` configured in channelConfig. It documents this feature:
- https://github.com/livingdocsIO/livingdocs-editor/pull/3451
- https://github.com/livingdocsIO/livingdocs-server/pull/2922
More documentation for this is to be added once the feature grows in functionality.
=> feat(includeServices): add minimal example for includeServices in channel config

concepts/copying-documents/document_copy_feature.md
Related:
- server: (needs server change to make `channelHandle` optional)
https://github.com/livingdocsIO/livingdocs-server/pull/2930
- We should update/remove the images that refer to `layout`
- Go through the document and check what is outdated
=> fix(copy): update copy guide

reference-docs/editor-api/vue-component-registry.md, reference-docs/includes/server_customization.md
1. this changes the order of include ui customizations as follows to better reflect our preferences:
- vue-component (new)
- iframe-modal (added doc about postMessage interface for passing `params`)
- angular-component (untouched)
- angular-modal (untouched)
2. the vue component type `includeParamsSidebarForm` is added to the vue registry docs
=> doc(includes): improve includes documentation

reference-docs/editor-configuration/text-editing.md, reference-docs/project-config/README.md
Related PRs:
- https://github.com/livingdocsIO/livingdocs-server/pull/3150
- https://github.com/livingdocsIO/livingdocs-editor/pull/3909
This adds an example of a `deliveries` config to the project config.
=> deliveries: add an example of a deliveries config to the project config

guides/add-custom-proofreading-task.md
Adds the flag "realtimeNotification" to the `li-task-v2` documentation
=> fix: add realtimeNotification flag to the task documentation

reference-docs/editor-configuration/metadata.md
We take the label from `ui.label`, not `ui.config.label` in the metadata forms. This PR fixes the examples accordingly.
This is the code to read the label: https://github.com/livingdocsIO/livingdocs-editor/blob/master/app/features/metadata/metadata_forms/metadata_form.js#L137
=> fix(metadata): fix examples with label

reference-docs/includes/article_and_list_includes.md
A customer notified us that the current documentation is not clear and wasted some time trying to get the inline-list editing feature to work.
Thus we added a small note.
=> chore(includes): add note about a required config for a feature

getting_started.md, guides/access_rights.md, guides/add-custom-realtime-proofreading-dashboard.md, guides/add_customizations.md, guides/create_designs.md, guides/github-login.md, guides/hugo-dnd.md, guides/image-services.md, guides/push_notifications.md, guides/setup_multilanguage.md, guides/setup_windows.md, guides/validate_tasks.md, reference-docs/includes/embed_and_list.md, reference-docs/project-config/content_types.md
More of the same link fixes as in PR #347, but for the service branch this time. I couldn't fix as many links as I managed in the other PR as there seems to be some missing documentation regarding Elasticsearch indexing, webhooks, and metadata.
=> chore(links): Fix broken service links

SUMMARY.md, guides/embedded_documents.md
With `release-2020-12` we shipped a first iteration of an `Editable Teasers` feature. There are some caveats that are mentioned in the docs. Nevertheless having a configuration example and a little introduction into what this feature means can be helpful to have in the docs.
This PR adds that minimal explanation and examples.
=> doc(embedded documents): add minimal embedded documents guide

SUMMARY.md, guides/article_teasers.md, guides/embedded_documents.md, reference-docs/includes/editor_customization.md
Relations:
- Server: https://github.com/livingdocsIO/livingdocs-server/pull/3385
- Editor: https://github.com/livingdocsIO/livingdocs-editor/pull/4152
- Framework: https://github.com/livingdocsIO/livingdocs-framework/pull/533
=> doc(teasers): add docs for paramsSchema li-reference and paramsSchemaExtension teaser includes

SUMMARY.md, guides/access_hooks.md
I just documented the current alpha state. If we change that in the future, we can update the documentation and break the API.
Original PR: https://github.com/livingdocsIO/livingdocs-server/pull/2445
Original Specification (outdated): https://github.com/livingdocsIO/livingdocs-planning/issues/2664 
Related Topic: ABAC (Access Control) - https://github.com/livingdocsIO/livingdocs-server/pull/2473
=> Add access hook doc

reference-docs/project-config/settings.md
A modified version of the enterprise docs which focuses more on the Project Config UI, and includes some additional information which was located in the server includes page.
=> doc(includes): Add interaction blocker details [service]

SUMMARY.md, guides/media_library.md, reference-docs/project-config/design.md
This adds a guide for the media library configuration walking through all the named crops configurations as well.
Also, the namedCrops are added to the designSettings example.
The extension of the `doc-image` documentation will follow in a separate PR.
=> Media library guide

SUMMARY.md, reference-docs/content-model/references.md
I'm not sure if this should be listed as a content model, or have its own section directly under "Reference Docs".
Examples taken from:
- https://github.com/livingdocsIO/livingdocs-server/pull/3341
- https://github.com/livingdocsIO/livingdocs-server/pull/3383
=> doc(references): Add references content model

content/enterprise/guides/includes/embedded-documents.md, content/enterprise/reference-docs/content-model/directives.md, content/enterprise/reference-docs/editor-api/document-drag-drop.md
Update occurrences of doc-link and doc-html to the new object format.
=> fix(docs): update doc-html and doc-link examples

content/enterprise/guides/integrations/import-legacy-system-documents.md, content/enterprise/reference-docs/server-api/import_api.md
Server PR: https://github.com/livingdocsIO/livingdocs-server/pull/3569
Add `publicationDate` docs and some more numbers on estimations of how fast imports currently are.
=> fix(import-api): update import docs

content/enterprise/reference-docs/project-config/deliveries.md
Mention to not forget to index the `slug` metadata-property  of articles for the internal document feature to work correctly with it
=> docs: small addition to setting up delivery configs

package-lock.json, package.json
This ends up adding quite a few packages. Should I look for another way?
The old command would open the browser before the server started, requiring a page refresh. Now it waits for the port to respond before opening the browser.
=> chore(npm): Make start script cross-platform

content/enterprise/guides/sitemaps-and-feeds.md
Server-PR: https://github.com/livingdocsIO/livingdocs-server/pull/3664
Issue: https://github.com/livingdocsIO/livingdocs-planning/issues/4277
As we shipped the new Sitemaps API, we want to provide some guidelines on how to integrate the Sitemaps and Feeds for a delivery.
=> Guide on how to generate Sitemaps & Feeds

content/enterprise/guides/revoke-media.md, content/enterprise/reference-docs/server-api/events.md, content/enterprise/reference-docs/server-configuration/webhooks.md
Relations:
- Issue: https://3.basecamp.com/4910529/buckets/19620057/documents/3884808654
- https://github.com/livingdocsIO/livingdocs-server/pull/3809
- https://github.com/livingdocsIO/livingdocs-editor/pull/4516
Remaining questions:
1. Should we make a media library section in the guides, split the existing content and add this as another page there?
2. Alternatively, could this be a workflow where we add suggestions about reviewing references and replacing the image?
3. Should I add some more examples? If so, what?
=> feat: Add revoke media page and events

content/reference-docs/editor-configuration/image-cropping.md
Setting a non-null `maxArea` leads to behavior that is probably not desired in most cases in combination with "free" cropping (without fixed aspect ratio), so I suggest it to `null` in the code sample.
Case in point: T-Online were confused by this behavior 👇
https://user-images.githubusercontent.com/47303530/132364105-d2370395-73ed-4ec5-a67f-dcc9b102d409.mov
=> chore: More reasonable sample value for maxArea

content/reference-docs/project-config/content-types.md
I've added a short introductory sentence, and moved the comparison with the list assignment feature to the end of the first paragraph.
Change request: https://github.com/livingdocsIO/documentation/pull/433#discussion_r745489789
=> fix: Improve document inbox explanation

content/reference-docs/document/metadata/_index.md
- Add quick example with `hideFromForm` to the docs. It's not ideal but better that if it is not mentioned anywhere.
=> fix(metadata): add hideFromForm example

content/operations/releases/release-2021-09/release-2021-09.md
The list of breaking changes is now the same as the list of referenced PRs further down.
(discovered while migrating heute.at to 2021-09)
=> fix: Add 4 missing callback support removals in 2021-09 release notes

content/operations/releases/master/master.md, content/reference-docs/project-config/media-types.md, themes/hugo-docs/layouts/partials/added-in.html, themes/hugo-docs/layouts/shortcodes/added-in.html, themes/hugo-docs/layouts/shortcodes/api-example.html
- Added an alias to the master release page so that added-in can support upcoming releases (e.g. release-2022-03)
- Changed the api-example template to use `if` instead of `while` as it's easier to understand, and the while scope was not used
- Created an `added-in` partial, which the existing shortcode now uses
- Added support for block `added-in` which can be used to add a margin bottom (`p` element instead of `span`)
- Extended the api-example template with added-in partial so that new endpoints can indicate when they were added
I couldn't find a way for the `.Get 0` in the "added-in" shortcode to work with custom contexts, which would have allowed me to use the shortcode directly from the "api-example" shortcode. The only way around it that I could find was to use a partial template. …
=> Refactor of added-in shortcode

content/reference-docs/project-config/settings.md, themes/hugo-docs/layouts/partials/added-in.html
Current URLs are https://docs.livingdocs.io/operations/releases/%7b%7b%20.release%20%7d%7d/%7b%7b%20.release%20%7d%7d/ instead of https://docs.livingdocs.io/operations/releases/release-2022-03/release-2022-03/ because the template variables are not parsed during variable assignment.
=> fix(added-in): Fix URL in shortcode and partial

content/reference-docs/project-config/content-types.md
The content type schema can be found here: https://github.com/livingdocsIO/livingdocs-server/blob/bc1086f2482d4fa7124b0b55b0223ebc95ff0733/app/features/channel-configs/config-properties/content-types/content_types_schema.js#L119-L127
=> fix: Move deliveryLinks out of frontend in contentTypes.editor schema

content/reference-docs/project-config/editor-settings.md
Relations:
- Issue: https://livingdocs.slack.com/archives/C019L2F33N2/p1646321217515999
- Related PR's: https://github.com/livingdocsIO/documentation/pull/471
I've restored and added some notes to make it clear when the "Main Navigation Groups" change was introduced.
=> fix: Restore main navigation legacy config information

content/guides/documents/includes/list-teasers.md
The properties are defined in the `design_settings` and we shouldn't assume in the documentation that customers use a specific design.
=> remove design specific property

content/guides/integrations/retresco.md, content/reference-docs/project-config/settings.md
Relations:
- https://github.com/livingdocsIO/livingdocs-server/pull/4415
- https://github.com/livingdocsIO/livingdocs-editor/pull/5205
This PR adds an explanation about the `enableLiveAnalysis` boolean option added to the project config.
=> feat(retresco): Document live analysis option

content/reference-docs/editor-extensions/editor-configuration/text-editing.md
Seems that `spellcheck/check` path along with the `?text=<value>` query are added to the configured host.
=> fix: custom spellcheck service url

content/reference-docs/editor-extensions/editor-configuration/editing-features.md
Whilst fixing ongoing bugs with the text multi selection I added the ability to disable text-multi selection with [this PR](https://github.com/livingdocsIO/livingdocs-editor/pull/5416)
I added this to the docs and in the meantime updated the fact that multi-component select no longer requires the shift key shortcut.
=> fix(mult text select): optional

content/reference-docs/editor-extensions/editor-configuration/text-editing.md
This was added a while back, here is the doc: https://github.com/livingdocsIO/livingdocs-editor/pull/4617
=> textcount: add textcount.showEditableCount doc

content/guides/documents/includes/document-teasers.md
This extends the Teaser Guide with information about the `contentType.teaserComponents` and `contentType.editor.documentEditingToolbar.dashboards` configs.
=> doc: teaser drag and drop

content/operations/releases/master/master.md
The two following commits ended up in release v80.39.21 due to build failures:
- Fix: Ensure UI updates when images/videos are edited in Embedded Documents
- Dashboards: Show correct contentType selection on create from custom dashboards
=> fix: Remove extra builds from PRs to Categorize

content/guides/documents/includes/document-teasers.md
Updated the documentation for the teaser drag and drop to dashboards after difficulties setting it up for SZ and SMB. 
Confirming the requirement for 'documentType' on baseFilters and adding the required import and export configs in project configs.
=> fix(configs required for drag and drop): updated

content/reference-docs/server-extensions/include-functions/_index.md
Updating the list of oEmbed providers in the include function page within reference-docs based on the list in the guide.
=> fix: Add new oEmbed providers to reference-docs

content/reference-docs/server-extensions/logging.md
- Related PRs: https://github.com/livingdocsIO/livingdocs-server/pull/4748
Refers to request in BaseCamp task -> https://3.basecamp.com/4910529/buckets/19910261/todos/4933699073
Extend logging options documentation (base, formatters (bindings, log)).
=> Add logging options to configure `pino` with comments

content/guides/integrations/desknet/index.md, content/operations/releases/release-2022-09.md, content/reference-docs/document/metadata/metadata-plugin-list.md, content/reference-docs/project-config/content-types.md, content/reference-docs/project-config/settings.md
- Added Automatic Placement configuration to the Desk-Net Integration guide
- Changed setup in the guide from `li-desknet-platforms` to `li-desknet-schedule`
- Added latest config for Desk-Net Schedule UI changes (filters, custom table dashboard)
- Added missing configs to reference docs
- Added li-desknet-schedule to the metadata plugins list
- Moved title sync config to the correct location
- Updated release notes
=> Add Desk-Net Schedule Extensions + Production Features

content/reference-docs/project-config/content-types.md
If regular content types are added to the inbox configs for non-page content types then they appear in the search modal and can be added to their inboxes. However, we do not yet support doing anything with them (This is planned for January 2023). As the support is incoming, rather than make the schema stricter I have instead updated the documentation to reflect the best config. This means that now the "Put into inbox" button for non page-types will only show pages (if they have an inbox set up). However, they can still receive images and videos which can then be dragged directly into the article itself.
=> Clarify document inbox for different content types

content/reference-docs/server-extensions/livingdocs-server-cli.md
Remove `parse-channel-config-v1-to-v2` command from `livingdocs-server `CLI
=> Remove parse-channel-config-v1-to-v2 command from livingdocs-server CLI

content/reference-docs/document/metadata/metadata-plugin-list.md
Remove the old default component name in the `li-transcoding-state` metadata plugin docs.
Related PR: https://github.com/livingdocsIO/livingdocs-editor/pull/5744
=> Update `li-transcoding-state` Default UI docs

content/reference-docs/project-config/editor-settings.md
Add new `onlyOnComponents` property to the `altTextPrefilling` config. I've changed the page structure slightly to make it easier to add a more detailed description and the release version which contains the new feature.
=> Add onlyOnComponents to altTextPrefilling

content/reference-docs/project-config/editor-settings.md
Added a simple config for the component prefix on the `directiveName` property (e.g. `image.` in `image.source`). I also added a sentence or two explaining it.
=> Add component prefix to componentDirectivesPrefilling

content/guides/authentication/access-rights/index.md
Update description of the scope for permissions for data records from readData to readDataRecords as per the editor expected scope.
=> fix(DataRecords): correct scope definition

content/guides/documents/document-design/embedded-design/index.md
Extend the referenced to embedded design migration Documentation.
=> extend design migration

content/operations/releases/release-2022-09.md
Under `security` section I included cheerio PR link. -> https://github.com/livingdocsIO/livingdocs-server/pull/4838
=> Update release notes [release-2022-09] to include cheerio modification PR

content/operations/releases/release-2022-09.md
Add under security section Google Vision PR link. -> https://github.com/livingdocsIO/livingdocs-server/pull/4833
=> Update release notes to include Google vision and Translate security PR

content/operations/releases/old/release-2020-07.md, content/reference-docs/server-extensions/server-configuration/_index.md
While updating the example server in the upstream (/livingdocsIO/livingdocs-server/pull/4840) we noticed that the description of this feature could be improved. Including an example on how to retrieve the document from the documentId and the support to previewUrl.
=> fix(custom preview): improve feature description

content/guides/editor/notifications/index.md, content/reference-docs/server-extensions/roles.md, content/reference-docs/server-extensions/server-configuration/_index.md
Relations:
- PRs: https://github.com/livingdocsIO/livingdocs-server/pull/4814
Add new Roles feature to documentation under server configuration. Add comments on how `enableConsumers` interact with roles and how to best defined them for your server instances.
=> Introduce Roles and how it interacts with `enableConsumers`

content/reference-docs/public-api/get-started.md
As discussed in the presentation we can mention OpenAPI in the Public API docs
=> fix: add info about openapi

content/operations/releases/master.md
Relations:
- Documentation: https://github.com/livingdocsIO/documentation/pull/583
- Server PR: https://github.com/livingdocsIO/livingdocs-server/pull/4954
- Editor PR: https://github.com/livingdocsIO/livingdocs-editor/pull/5990
- 💥 Drop support for node 14. Please upgrade to node v18.
=> Drop support for node 14

content/reference-docs/server-extensions/livingdocs-server-cli.md, content/reference-docs/server-extensions/server-configuration/_index.md
Relations:
- Related PRs: https://github.com/livingdocsIO/livingdocs-server/pull/4478
Include documentation on new `db` object configuration to describe `migrate` and `write` users added with PR stated above.
=> Add functionality added to `livingdocs-server database create`

content/learn/on-premise-setup.md
Relations:
- Issue: https://github.com/livingdocsIO/livingdocs-planning/issues/4770
As part of the bug mentioned above, we decided the issue does not affect the customers, but we would like them to refer them to the docs if they complain. This PR introduces and explanation on how to configure Pusher Channels and why it is a good idea.
=> Include explanation on why disable `authorized connections` in Pusher is a good idea

content/reference-docs/editor-extensions/editor-configuration/text-editing.md
Fixed a copy & paste error where I added the wrong release link to the new spellcheck config that was added with release 2022-11
=> Correct spellcheck underline release link

content/reference-docs/server-extensions/server-configuration/_index.md
Relations:
- Livingdocs Server PR: https://github.com/livingdocsIO/livingdocs-server/pull/4982
- 🎁 Add tls documentation to the redis config
=> Document the redis tls config

content/guides/editor/document-copy/index.md
We never implemented or supported this config. The docs are 6 years old. This removes unsupported suggested config
=> Remove the not supported Copy Function in document copy config

content/guides/documents/includes/oembed/index.md, content/reference-docs/server-extensions/include-functions/_index.md
Related PR: https://github.com/livingdocsIO/livingdocs-server/pull/4910
- Adding Dailymotion to the list!
- Removing added-in release-2022-03 as it's no longer new.
=> Add Dailymotion to oEmbed providers

content/operations/releases/master.md, content/operations/releases/old/release-2017-08.md, content/operations/releases/old/release-2018-01.md, content/operations/releases/old/release-2018-02.md, content/operations/releases/old/release-2019-07.md, content/operations/releases/release-2021-03.md, content/operations/releases/release-2021-06.md, content/operations/releases/release-2022-11.md
Relations:
- Issue: https://github.com/livingdocsIO/livingdocs-planning/issues/4767
- https://github.com/livingdocsIO/livingdocs-server/pull/4957
- https://github.com/livingdocsIO/livingdocs-server/pull/4992
It would be great if you could both give the text in the latest release notes a review.
Is "Breaking Changes" the correct section? All other manual migrations have been listed here, although it's not technically a breaking change this time.
Do we need to specify pre or post deployment? I suppose post deployment makes the most sense for a fix like this.
=> Fix first publication date

content/guides/integrations/li2xliff/index.md, content/reference-docs/project-config/settings.md
We have built our installable li2Xliff guide to offer CAT translations for customers. This is implemented by the NZZ. 
I have tried to write as simple a guide as possible but with enough detail. There are links to the webhook and access-hook docs as these are required to implement it. I have given example functions for these, but otherwise kept it simple on the configs you can hand li2xliff and what these configs do.
=> Adding a li2Xliff guide to the documentation

content/guides/editor/document-copy/index.md
Whilst supporting Dumont on a custom copy function I suggested using this config but from the comment it seems we never enabled it - Lorenzo also searched the server, editor and framework and said we never configured it. 
So I thought it was worth removing from the docs as it is misleading to have a config which we know does nothing.
=> Copy unknown components config removed from copy/transform documentation

content/customising/server-configuration/_index.md
Relations:
- Related PR: https://github.com/livingdocsIO/livingdocs-server/pull/4926
Configuration used to report back stack traces on 4XX error responses.
=> Add `httpServer.showStackTraces` to Server configuration

content/reference/document/includes/editor-customization.md
I am working through the bluewin BTS and anytime I find some reference to making things in angular I will remove it. 
This is just a WIP and I will add commits to it as I go then finish the Pr.
=> Remove angular from include docs

content/customising/server-configuration/_index.md
As discussed after Netcetera reported our docs said all prefix names would be renamed, but it is only custom and publication indexes
=> Update the description of indexNamePrefix

content/reference/project-config/content-types.md
A simple comment to let users know they can use an editorWrapper as the base section for a content type.
=> Add editor Wrapper to content type docs

themes/hugo-docs/assets/elements/api-example.scss, themes/hugo-docs/layouts/shortcodes/api-example.html
=> Align anchor on public api section titles

content/reference/document/metadata/metadata-plugin-list.md
Add comment that `li-buy-in` plugin is only usable when planning system is enabled.
=> Add planning system notice in `li-buy-in` reference docs

content/customising/advanced/editor-configuration/editing-features.md
Seems this has gone out of our codebase quite a while ago. Unfortunately, it was still in the docs and in pretty much every editor config ...
=> Remove documentation of history statistics

content/operations/releases/_index.md, themes/hugo-docs/layouts/partials/topbar.html
As discussed/decided we want to call the Technical Release Notes in the Documentation `Technical Release Notes`.
=> fix: rename Release Notes to Technical Release Notes

content/guides/authentication/attribute-based-access-control.md, content/guides/editor/push-notifications/index.md
Relations:
- Related PR: https://github.com/livingdocsIO/livingdocs-server/pull/5505
Support for `serverConfig.policies` was deprecated 3+ years ago. It's time to remove it.
=> Remove server config policies example from ABAC guide

content/guides/editor/publish-control/delivery/index.md, content/reference/project-config/deliveries.md, content/reference/webhooks/_index.md
- 🎁 Add documentation for draft delivery builds
- 💎 Update existing configuration for builds and use 'delivery builds' as a name for this feature
=> Update delivery build documentation

content/reference/document/includes/server-customization.md
After writing some paramsSchema includes as part of Bluewin BTS and infobox improvements, along with supporting Netcetera writing ones with li-document-reference/s, I wanted to just tidy up the documentation a little bit. 
I moved the paramsSchema to the top to try and promote it as the most viable option. And reminded users not to write any custom code without talking to us first. 
I also added the option of rendering a publication in the renderFunction. 
Happy to discuss 👍
=> fix(includes): moved paramschema to be more prominent

content/guides/media-library/media-library-setup/index.md
Muhamet at Centralsoft sent me a message as he noticed that we removed the ui.component config for this plugin in the [november release](https://docs.livingdocs.io/operations/releases/release-2022-11/#break-metadata-plugin-li-desknet-integration--li-transcoding-state-), but it was still in the docs. 
This PR just removes it from the example config.
=> fix(transcoding plugin): component removed

content/operations/releases/release-2022-03.md, content/reference/public-api/drafts/_index.md, content/reference/public-api/drafts/latest-draft-beta.md, content/reference/public-api/publications/_index.md, content/reference/public-api/publications/latest-publication-beta.md, content/reference/public-api/publications/latest-publication.md, content/reference/public-api/publications/latest-publications-beta.md, content/reference/public-api/publications/latest-publications.md, content/reference/public-api/publications/publication-events.md, content/reference/public-api/publications/references.md, content/reference/public-api/publications/renditions.md, content/reference/public-api/publications/search.md, redirects.map
- Search is within the Publications path (api/v1/publications/search), so the file and menu location have been moved.
- Latest Draft Beta is not part of Publications, so the file and menu location have been moved.
- Setting a menu parent to "Publications " instead of "Publications" creates a different menu item. I had to copy/paste to figure out why it wasn't working as expected. I don't think there was a reason for this trailing space, so I removed it.
- I have setup nginx redirects for the two moved pages.
=> Organise drafts and search

content/customising/server-configuration/_index.md
I removed this from the processing object for clarity that it should only be in one place - the uploadRestrictions. 
I updated the information in the testrail case and re-tested and it works 👍
=> fix(image config): remove max file size

content/operations/releases/release-2023-07.md
I was confused by Sublime merge search :) There are commits for `ui.component` removal but have not been merged: https://github.com/livingdocsIO/livingdocs-server/pull/5811
=> `ui.component` removal wasn't merged, it will be done next release

content/reference/document/metadata/plugins/li-text.md, themes/hugo-docs/layouts/shortcodes/release.html
The `< release >` shortcode should be inline, but the trailing newline in the template caused the text to wrap. Using `{{- -}}` instead of `{{ }}` is used to remove any newlines surrounding the code block. 
Before:
After:
=> Remove newline after `< release >` shortcode

content/guides/editor/filter-migration.md
This guide explains the process of moving from the old display filter and base filter format to the new query DSL format. It could be deleted in ~6 months. Some of the data could probably be moved into the metadata plugins documents, but there's probably not a lot of overlap. Perhaps it makes more sense to merge in into another guide later.
=> Add Filter Migration guide

content/customising/server-configuration/_index.md
This is no longer used, instead image metadata is only enforced when a property is required, this is documented already [here](https://github.com/livingdocsIO/documentation/blob/19ef879178a901c9e2c899742bbc5a1622a514c8/content/guides/media-library/media-library-setup/index.md#L47)
=> Remove 'enforcing image metadata' configs from documentation

content/customising/server-configuration/_index.md
Relations:
- Related PR: https://github.com/livingdocsIO/livingdocs-server/pull/5909
=> Add mediaLibrary.image.processing.failOn to server config

themes/hugo-docs/assets/search.js
Relations:
- Related PR: https://github.com/livingdocsIO/documentation/pull/710
This allows matches for "registerInitializedHook", when previously you would need to search for "liServer.registerInitializedHook".
This needs some testing before merging.
=> Separate search strings on any non-word character

content/operations/releases/release-2022-07.md, content/operations/releases/release-2023-07.md
The July 2023 release should now be visible in search. It looks like we only keep the last year visible, as release-2022-05 was already hidden from search results, so I've excluded release-2022-07 too.
=> Show last year of releases in search results

content/guides/editor/filter-migration.md
This has come up a couple of times, and even I struggle to remember to query the nested property value, and I wrote the documentation and wrote some of the code! :grin: Hopefully having a section title makes it much more obvious, and gives people a link on the right when there are issues migrating.
=> Add more details about migrating filters for references

content/customising/server/server-hooks.md
Warn downstreams not to try and directly mutate metadata.
=> fix(publish hook): warn not to mutate metadata

content/guides/editor/multi-language-content/index.md, content/reference/document/metadata/plugins/li-language.md
We will have to also include it in the Technical release notes.
=> Add deprecation for `label` property in `li-language` metadata

content/reference/sdk/_index.md
Replacing some old `developers.livingdocs.io` links.
=> Update links in SDK reference docs

content/operations/releases/release-2023-03.md, content/operations/releases/release-2023-07.md, content/operations/releases/release-2023-09.md, content/operations/releases/release-2023-11.md
Browser version support in previous releases didn't reflect the actual feature set used in the editor.
`array.prototype.at()` was introduced 1.5 years ago, but Safari started support with 15.4.
=> Bump browser versions from march to november releases

content/customising/advanced/editor-configuration/display-filter.md
Note added as a result of a conversation in Slack: https://livingdocs.slack.com/archives/C4TGTEC3F/p1694691100998669?thread_ts=1694614903.890039&cid=C4TGTEC3F
=> Configuring metadata display filters for multiple content types

content/operations/releases/release-2023-11.md
As Ralph mentioned in PR [#768](https://github.com/livingdocsIO/documentation/pull/758), it makes sense to include the original functions replaced by liServer extensions
=> Add original api functions replaced by liServer extensions

content/customising/server-configuration/single-sign-on.md, content/customising/server/data-source-api.md, content/customising/server/server-hooks.md, content/guides/authentication/azure-ad-login/index.md, content/guides/documents/includes/oembed/index.md, content/guides/documents/includes/twitter-embed/index.md, content/guides/documents/includes/youtube-embed/index.md, content/guides/editor/document-creation-flow.md, content/guides/editor/image-gallery.md, content/guides/editor/menu-tool/index.md, content/guides/integrations/desknet/index.md, content/guides/integrations/li2xliff/index.md, content/guides/media-library/media-sources/index.md, content/guides/organisation/sitemaps-and-feeds.md, content/guides/setup/server-customization.md, content/operations/releases/old/release-2017-12.md, content/reference/document/includes/server-customization.md, content/reference/project-config/editor-settings.md
- 🎁 Use new `liServer.register...()` methods everywhere.
- 🎁 Replace `liServer.features.register()` with `liServer.registerServerRoutes()`
- 🔧 Use `daily-planet` as example project handle
=> Use new liServer.register methods

content/reference/document/includes/introduction.md, content/reference/project-config/content-types.md
Because we don't want customers to use renditions anymore, I removed the doc. I kept the renditions doc in the public API, because the API still supports that requests.
=> Remove rendition doc

content/guides/setup/import-legacy-system-documents.md, content/reference/public-api/add-delivery-status.md, content/reference/public-api/composition-api.md, content/reference/public-api/document-categories.md, content/reference/public-api/document-command-api.md, content/reference/public-api/document-lists.md, content/reference/public-api/drafts/incoming-references.md, content/reference/public-api/drafts/latest-draft-beta.md, content/reference/public-api/get-started.md, content/reference/public-api/health.md, content/reference/public-api/imports/documents.md, content/reference/public-api/imports/images.md, content/reference/public-api/imports/media-library-entries.md, content/reference/public-api/imports/videos.md, content/reference/public-api/media-library.md, content/reference/public-api/menus.md, content/reference/public-api/project.md, content/reference/public-api/publications/latest-publication-beta.md, content/reference/public-api/publications/latest-publication.md, content/reference/public-api/publications/latest-publications-beta.md, content/reference/public-api/publications/latest-publications.md, content/reference/public-api/publications/publication-events.md, content/reference/public-api/publications/references.md, content/reference/public-api/publications/renditions.md, content/reference/public-api/publications/search.md, content/reference/public-api/retresco.md, content/reference/public-api/routing.md, content/reference/public-api/sitemaps.md
Replace `Accept` header with `Content-Type` since requests might be ignored when `Content-Type` header is not defined.
=> Replace Editor proxy URL with server URL

content/operations/releases/release-2023-09.md
Reduce confusion, when link doesn't work
=> Remove link to Ticker feature documentation as it didn't exist

content/guides/setup/editor-customization.md
Relations:
- Related PRs: https://github.com/livingdocsIO/livingdocs-editor/pull/8074
=> Remove unsupported example calling `initializeOembedMetadataExtractor()` in editor customizations

content/reference/document/metadata/plugins/li-boolean.md, content/reference/document/metadata/plugins/li-color.md, content/reference/document/metadata/plugins/li-date.md, content/reference/document/metadata/plugins/li-datetime.md, content/reference/document/metadata/plugins/li-enum.md, content/reference/document/metadata/plugins/li-external-id.md, content/reference/document/metadata/plugins/li-integer.md, content/reference/document/metadata/plugins/li-moderated-collab.md, content/reference/document/metadata/plugins/li-publish-date.md, content/reference/document/metadata/plugins/li-text.md, content/reference/webhooks/_index.md, themes/hugo-docs/layouts/metadata-plugins/single.html
Related PRs:
- https://github.com/livingdocsIO/livingdocs-server/pull/6461
- https://github.com/livingdocsIO/livingdocs-server/pull/6499
- https://github.com/livingdocsIO/livingdocs-server/pull/6648
- https://github.com/livingdocsIO/livingdocs-server/pull/3359
- Extends the documentation on webhook conditions and change filters.
- Adds an indicator to metadata plugin pages to show which ones support metadata property conditions.
=> Extend documentation on webhook conditions and change filters

content/reference/webhooks/_index.md
Related PRs:
- https://github.com/livingdocsIO/livingdocs-server/pull/6658
- Add `publication.update` to supported webhook events
=> Add publication.update event to webhooks documentation

content/operations/releases/release-2023-11.md, content/operations/releases/release-2024-01.md, content/operations/releases/release-2024-03.md, content/operations/releases/release-2024-05.md
We have patched vulnerabilities in all supported releases and we want customers to know they have been patched. This PR adds information on what was patched and to which release it was patched.
=> Add vulnerability information for the latest 3 releases

content/guides/media-library/image-services.md, content/operations/releases/release-2024-03.md
A guide to building the URL in deliveries after our changes in the March release. 
I also added a link in the march release.
=> fix(image url building in deliveries): added

content/reference/public-api/composition-api.md
Whilst using the composition API today I noticed that if you add `fields: ['includes']` and `resolveIncludes: true` then the content does not resolve the includes, they are only resolved in the separate array. 
I added this as a simple sentence to make sure people don't do what I did and spend ages thinking my include service wasn't resolving anything!
=> fix(composition api): clarity on fields vs includes

content/operations/releases/release-2024-05.md
- Add deprecation of dashboards of type `dashboard` to release notes
- Add deprecation of custom Angular dashboard cards to release notes
=> Release-2024-05 dashboard deprecations

content/operations/releases/release-2024-03.md, content/reference/project-config/content-types.md
I don't think we support audio and html component types here, at least I have not found any other references in the documentation and at a first glance also no explict handling in the code
=> docs(defaultComponents): remove audio and html component types

content/operations/releases/release-2024-05.md
Delete the `Caveat` section and add the release notes link. 
Add a description for the File Import via Public API
=> Add file import feature description and cleanup release notes for May release

content/operations/releases/release-2024-05.md
We added a small note about the fact that textCount has to be camelCased in the new config location
(because we came across this issue ourselves)
=> Update May release note about textCount

content/customising/server-configuration/_index.md, content/operations/external-services.md, content/operations/releases/release-2023-11.md
Relations:
- Issue: https://livingdocs.slack.com/archives/C4TGTEC3F/p1718310357740409?thread_ts=1718308138.147799&cid=C4TGTEC3F
For full realtime functionality it is important that customers enable the "Enable client events" setting using the Pusher dashboard.
=> Inform customers to enable client events for Pusher

content/guides/editor/icons.md
Relations:
- Issue: https://github.com/livingdocsIO/livingdocs-bugs/issues/5296
We no longer recommend using upstream components. This part of the documentation has not been updated when that decision was made.
=> fix(icons): Remove Icons in UI Extensions section

config.yaml, themes/hugo-docs/layouts/partials/html-header.html
Had a Hugo deprecation error in the newest version even though it should only be removed from hugo v 0.135.0 on with hugo version `0.134.2` 🤷
> ERROR deprecated: .Site.GoogleAnalytics was deprecated in Hugo v0.120.0 and will be removed in Hugo 0.135.0. Use .Site.Config.Services.GoogleAnalytics.ID instead.
=> fix(analytics): change google analytics path

config.yaml, redirects.map, themes/hugo-docs/layouts/partials/html-header.html
Noticed missing redirects which are used on livingdocs.io
=> Fix missing redirects

content/operations/releases/release-2024-09.md
- https://github.com/livingdocsIO/livingdocs-editor/pull/8777
=> Extend description of editor URLs breaking change

content/operations/releases/release-2024-05.md, content/operations/releases/release-2024-07.md, content/operations/releases/release-2024-09.md, content/operations/releases/release-2024-11.md
Relations:
- Related PRs: https://github.com/livingdocsIO/livingdocs-server/pull/7355 https://github.com/livingdocsIO/livingdocs-editor/pull/9084
We want to keep vulnerability updates on the documentation, including old releases.
=> Update release notes for latest releases to include latest security patches

content/operations/releases/release-2024-11.md, content/reference/public-api/document-command-api.md
Relations:
- https://github.com/livingdocsIO/livingdocs-server/pull/7373
- https://github.com/livingdocsIO/livingdocs-server/pull/7405
- https://github.com/livingdocsIO/livingdocs-server/pull/7395
New commands:
- `setComponentCondition`
- `setComponentStyle`
- `setIncludeDirective`
- `setLinkDirective`
- `setStyleDirective`
=> Add documentation for new commands

content/operations/releases/release-2024-11.md, content/reference/project-config/editor-settings.md
@ajwild can check video source policy and `componentDirectivesPrefilling`
@dfreier can check breaking for `appConfig.textcount` and deprecation on `contentTypes` in `li-document-search`
=> Clean up release notes and introduce operations steps

content/customising/advanced/editor-configuration/text-editing.md, content/reference/document/metadata/plugins/li-tree.md
Because of https://github.com/livingdocsIO/livingdocs-bugs/issues/5400
=> Mention config for relative paths and anchors in li-tree docs

content/operations/releases/release-2024-11.md
November release notes instruct to run this migration
`node db/manual-migrations/011-move-metadata.js `
It is probably actually referring to this one `011-move-revision-metadata`.
I updated it, waiting for your confirmation that this assumption was correct :)
=> fix: fix typo in db migration name

content/operations/releases/release-2025-01.md
Relations:
- Editor PR: https://github.com/livingdocsIO/livingdocs-editor/pull/9280
=> Add sass `@import` migration guide to release notes

themes/hugo-docs/layouts/index.searchindex.json, themes/hugo-docs/layouts/partials/html-header.html
This reverts commit c2c4b00119d40a628b1d4558528923a33a8d72cb to fix the build system. Once https://github.com/livingdocsIO/documentation/pull/929 is addressed, we can reapply this commit.
=> Revert gohugo deprecations fix

content/reference/project-config/deliveries.md
The deliveries need to be an empty array to not appear on a contentType. 
This updates the docs to explain this.
=> fix(deliveries docs): point out they must be empty config

README.md, package-lock.json, package.json
Hugo v139.0 introduces a new `--optionBrowser` feature, which opens the project in the browser. This eliminates the need for the additional `opener` dependency. The browser window opens only after the page is built. Previously, starting the project would first open an empty page.
=> Replace opener with hugo built-in --openBrowser option

content/customising/server-configuration/_index.md
I realised the kordiam server configuration wasn't added in the documentation. We want to have all config properties documented.
=> Include `kordiam` server config

content/operations/releases/release-2025-01.md
- Related PR: https://github.com/livingdocsIO/livingdocs-server/pull/7536
=> Legacy filter syntax in li-document-search base filters breaking change

content/operations/releases/release-2025-01.md, content/reference/document/metadata/plugins/li-kordiam-schedule.md, content/reference/document/metadata/plugins/li-system-boolean.md, content/reference/document/metadata/plugins/li-system-date.md, content/reference/document/metadata/plugins/li-system-datetime.md, content/reference/document/metadata/plugins/li-system-enum.md, content/reference/document/metadata/plugins/li-system-integer.md, content/reference/document/metadata/plugins/li-system-target-length.md, content/reference/document/metadata/plugins/li-system-text.md
- add system metadata release notes
- add the new system metadata plugins to the list
=> add system metadata plugins release info

content/customising/server-configuration/_index.md
Relations:
- Issue: https://3.basecamp.com/4910529/buckets/38087546/todos/7940308691
- Related PR: https://github.com/livingdocsIO/livingdocs-server/pull/7534
- 🍬 Enable table dashboard and teaser realtime updates by default
=> Realtime updates enabled by default in server config

themes/hugo-docs/assets/elements/history-button.scss
=> fix(history button): Safari

content/operations/releases/release-2025-05.md, data/releases.json
As part of the release cut we have to create a new page for the next release in the documentation repository. 
You still have to create another PR to update current/maintained/legacy status in the release pages. The PR shall be merged the day the release is announced.
- :building_construction: Create a new page for the next release in the documentation repository
=> Add release-2025-05 release documentation

content/operations/releases/release-2025-03.md, content/operations/releases/release-2025-05.md
New release needs the technical release notes to be cleaned up.
- Remove PRs to categorize after checking them
- Don't add `Deployment` section, as in release-2025-03, as we don't have migrations this cycle
- Added features and breaking change bullet points
- Added vulnerability patches (to release-05 and release-03)
=> Release Notes Cleanup for release-2025-05

content/reference/public-api/_index.md, content/reference/public-api/open-api.md, themes/hugo-docs/layouts/shortcodes/openapi-list.html, themes/hugo-docs/layouts/shortcodes/openapi.html
- Add a separate Open API page for the public API docs that is easier to find
- Add a list of all version specific Open API JSON documents
=> Add separate openApi page with links to all OpenAPI JSON files

content/customising/server/server-api/data-source-api.md, content/operations/releases/release-2025-05.md
- No longer sending the `documentId` in data source requests
=> Add breaking change release-2025-05

themes/hugo-docs/assets/elements/feature-info.scss
=> Adjust margins of feature info pill

content/customising/advanced/editor-configuration/editing-features.md
We firmly disabled comments on editable teasers [here](https://github.com/livingdocsIO/livingdocs-editor/pull/9082)
It wasn't documented so I thought I'd add it quickly.
=> fix(comments): confirm not enabled one ditable teasers

content/operations/releases/release-2025-09.md, data/releases.json
As part of the release cut we have to create a new page for the next release in the documentation repository.
You still have to create another PR to update current/maintained/legacy status in the release pages. The PR shall be merged the day the release is announced.
- :building_construction: Create a new page for the next release in the documentation repository
=> Add release-2025-09 release documentation

content/operations/releases/release-2025-07.md, content/reference/public-api/changelog/2025-07/channel-endpoints-deprecation.md, data/endpoints/get-channel-configuration.yaml, data/endpoints/get-project-config.yaml, data/endpoints/get-project-configuration.yaml, themes/hugo-docs/layouts/changelog/section.html
- ⚠️ Deprecation of `/project`, `/channelConfig` and `/channels/{channelHandle}` endpoints
=> Deprecate channel endpoints of public api

content/customising/advanced/editor-configuration/editing-features.md
- Related PR: https://github.com/livingdocsIO/livingdocs-editor/pull/1774
The `useHistoryRestore` property was implemented in 2018 and but longer existed at some point in 2019. Presumably this was used as a beta flag in case it caused problems.
=> Remove unused `useHistoryRestore` property

content/operations/releases/release-2025-11.md, data/releases.json
As part of the release cut we have to create a new page for the next release in the documentation repository.
You still have to create another PR to update current/maintained/legacy status in the release pages. The PR shall be merged the day the release is announced.
- :building_construction: Create a new page for the next release in the documentation repository
=> Add release-2025-11 release documentation
